"""FastAPI application entry point for Schnitzel backend."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="Schnitzel Backend",
    description="Schema-driven FastAPI backend generated by Schnitzel",
    version="0.1.0"
)

# Configure CORS for development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, replace with specific origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
async def root():
    """Root endpoint."""
    return {
        "message": "Welcome to Schnitzel Backend",
        "version": "0.1.0",
        "status": "running"
    }


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "service": "schnitzel-backend"
    }


# Import and register generated routes
try:
    from backend.app.generated.routes import router as generated_router
    app.include_router(generated_router, prefix="/api")
except ImportError:
    # Generated routes not yet available
    pass
