# Generated by Schnitzel Framework
# DO NOT EDIT - This file is auto-generated
# Generated at: 2025-12-04T10:38:59.359925
# Source: force_watch.yaml



from pydantic import BaseModel
from uuid import UUID


class User(BaseModel):
    id: UUID
