# Generated by Schnitzel Framework v0.1.0
# DO NOT EDIT - This file is auto-generated
# Generated at: 2025-12-05T12:09:09.071245
# Source: force_watch.yaml



from pydantic import BaseModel
from uuid import UUID


class User(BaseModel):
    # Fields
    id: UUID
