// Generated by Schnitzel Framework v0.1.0
// DO NOT EDIT - This file is auto-generated
// Generated at: 2025-12-05T18:45:40.022191
// Source: schema.schnitzel.yaml

import 'package:flutter_test/flutter_test.dart';
import 'package:promptduel/main.dart';

void main() {
  testWidgets('App loads home screen smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(const PromptduelApp());
    await tester.pumpAndSettle();

    // Verify that we see the home screen title
    expect(find.text('Promptduel'), findsWidgets);
  });
}
