// Generated by Schnitzel Framework
// DO NOT EDIT - This file is auto-generated
// Generated at: 2025-12-03T17:20:05.167732
// Source: schema.schnitzel.yaml

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';

part 'models.freezed.dart';
part 'models.g.dart';

@freezed
class User with _$User {
  const factory User({
    required String id,
    required String name,
    required String email,
    String? bio,
    @Default(true) bool is_active,
    required DateTime created_at,
    List<Post>? posts,
    List<Comment>? comments,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}

@freezed
class Post with _$Post {
  const factory Post({
    required String id,
    required String title,
    required String content,
    required String author_id,
    required DateTime created_at,
    User? author,
    List<Comment>? comments,
  }) = _Post;

  factory Post.fromJson(Map<String, dynamic> json) => _$PostFromJson(json);
}

@freezed
class Comment with _$Comment {
  const factory Comment({
    required String id,
    required String content,
    required String author_id,
    required String post_id,
    required DateTime created_at,
    User? author,
    Post? post,
  }) = _Comment;

  factory Comment.fromJson(Map<String, dynamic> json) => _$CommentFromJson(json);
}
