#!/usr/bin/env python3
"""
Final comprehensive test for F029: Python model generator creates models.py in correct output directory

This test validates all requirements from the feature specification.
"""

import sys
import shutil
from pathlib import Path
from datetime import datetime

# Add the schnitzel-cli/src directory to the Python path
sys.path.insert(0, str(Path(__file__).parent / "schnitzel-cli" / "src"))

from schnitzel.schema.models import SchnitzelSchema, Model, FieldDefinition
from schnitzel.generators.python.models import PythonModelGenerator


def test_generate_to_file():
    """Test the generate_to_file method comprehensively."""
    print("=" * 80)
    print("COMPREHENSIVE TEST: F029 - generate_to_file() Method")
    print("=" * 80)

    # Create test schema
    schema = SchnitzelSchema(
        models={
            "User": Model(
                name="User",
                description="User account",
                fields={
                    "id": FieldDefinition(type="uuid"),
                    "email": FieldDefinition(type="string", max_length=255),
                    "age": FieldDefinition(type="int", min=0, max=150),
                }
            )
        }
    )

    generator = PythonModelGenerator()

    # Test 1: Create file in new directory
    print("\nTest 1: Create file in new directory")
    print("-" * 80)

    test_dir = Path(__file__).parent / "test_f029_output"
    if test_dir.exists():
        shutil.rmtree(test_dir)

    output_path = generator.generate_to_file(schema, test_dir)

    assert output_path.exists(), "Output file should exist"
    assert output_path == test_dir / "models.py", "Output path should be correct"
    assert test_dir.exists(), "Output directory should be created"

    print(f"✓ File created: {output_path}")
    print(f"✓ Directory created: {test_dir}")

    # Test 2: Verify header content
    print("\nTest 2: Verify header content")
    print("-" * 80)

    content = output_path.read_text()
    lines = content.split('\n')

    assert lines[0] == "# Generated by Schnitzel Framework", "Line 1: Framework attribution"
    assert lines[1] == "# DO NOT EDIT - This file is auto-generated", "Line 2: Edit warning"
    assert lines[2].startswith("# Generated at:"), "Line 3: Timestamp header"
    assert lines[3] == "# Source: schema.schnitzel.yaml", "Line 4: Source schema"
    assert lines[4] == "", "Line 5: Empty line separator"

    print("✓ Header line 1: Framework attribution")
    print("✓ Header line 2: Edit warning")
    print("✓ Header line 3: Timestamp")
    print("✓ Header line 4: Source schema")
    print("✓ Header line 5: Separator")

    # Test 3: Verify timestamp format
    print("\nTest 3: Verify timestamp format")
    print("-" * 80)

    timestamp_line = lines[2]
    timestamp_str = timestamp_line.replace("# Generated at: ", "")

    # Validate ISO format by parsing
    try:
        parsed_time = datetime.fromisoformat(timestamp_str)
        print(f"✓ Timestamp is valid ISO format: {timestamp_str}")
        print(f"  Parsed as: {parsed_time}")
    except ValueError as e:
        print(f"✗ Timestamp is not valid ISO format: {e}")
        return False

    # Test 4: Verify custom schema source
    print("\nTest 4: Verify custom schema source")
    print("-" * 80)

    output_path_2 = generator.generate_to_file(schema, test_dir, schema_source="custom_schema.yaml")
    content_2 = output_path_2.read_text()

    assert "# Source: custom_schema.yaml" in content_2, "Custom source should be in header"
    print("✓ Custom schema source: custom_schema.yaml")

    # Test 5: Verify generated models are present
    print("\nTest 5: Verify generated models are present")
    print("-" * 80)

    assert "class User(BaseModel):" in content, "User model class should be present"
    assert "from pydantic import BaseModel, Field" in content, "Pydantic imports should be present"
    assert "from uuid import UUID" in content, "UUID import should be present"

    print("✓ User model class present")
    print("✓ Pydantic imports present")
    print("✓ Type imports present")

    # Test 6: Test with Path object
    print("\nTest 6: Test with Path object (not just string)")
    print("-" * 80)

    path_dir = Path(__file__).parent / "test_f029_path"
    if path_dir.exists():
        shutil.rmtree(path_dir)

    output_path_3 = generator.generate_to_file(schema, path_dir)
    assert output_path_3.exists(), "Should work with Path object"

    print(f"✓ Works with Path object: {output_path_3}")

    # Test 7: Test deeply nested directories
    print("\nTest 7: Test deeply nested directory creation")
    print("-" * 80)

    deep_dir = Path(__file__).parent / "test_f029_deep" / "a" / "b" / "c" / "d" / "e"
    output_path_4 = generator.generate_to_file(schema, deep_dir)

    assert output_path_4.exists(), "Deeply nested file should exist"
    assert deep_dir.exists(), "Deeply nested directory should be created"

    print(f"✓ Deep directory created: {deep_dir}")
    print(f"✓ File created: {output_path_4}")

    # Clean up
    print("\nCleaning up test directories...")
    shutil.rmtree(Path(__file__).parent / "test_f029_output")
    shutil.rmtree(Path(__file__).parent / "test_f029_path")
    shutil.rmtree(Path(__file__).parent / "test_f029_deep")

    print("\n" + "=" * 80)
    print("ALL TESTS PASSED!")
    print("=" * 80)
    print("\nFeature F029 fully validated:")
    print("  ✓ generate_to_file() method works correctly")
    print("  ✓ Creates output directory if it doesn't exist")
    print("  ✓ Handles deeply nested directories (parents=True)")
    print("  ✓ Writes models.py to correct location")
    print("  ✓ Adds proper header with:")
    print("    - Framework attribution")
    print("    - Edit warning")
    print("    - ISO format timestamp")
    print("    - Source schema info (customizable)")
    print("  ✓ Returns Path object of generated file")
    print("  ✓ Works with both string and Path inputs")
    print("  ✓ Overwrites existing files with warning")

    return True


if __name__ == "__main__":
    try:
        success = test_generate_to_file()
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"\n✗ TEST FAILED WITH ERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
