// Generated by Schnitzel Framework v0.1.0
// DO NOT EDIT - This file is auto-generated
// Generated at: 2025-12-06T13:01:51.516388
// Source: schema.schnitzel.yaml

import 'package:my_blog_shared/models/models.dart';
import 'package:my_blog/repositories/repositories.dart';

/// Fake implementation of UserRepository for testing.
///
/// Uses an in-memory list to simulate repository operations.
class FakeUserRepository implements UserRepository {
  final List<User> _items = [];

  @override
  Future<List<User>> getAll({
    int page = 1,
    int pageSize = 20,
    Map<String, dynamic>? filters,
    String? sortBy,
    String? sortOrder,
  }) async {
    return List.unmodifiable(_items);
  }

  @override
  Future<User> getById(String id) async {
    return _items.firstWhere((item) => item.id == id);
  }

  @override
  Future<User> create(User item) async {
    _items.add(item);
    return item;
  }

  @override
  Future<User> update(User item) async {
    final index = _items.indexWhere((i) => i.id == item.id);
    if (index >= 0) _items[index] = item;
    return item;
  }

  @override
  Future<void> delete(String id) async {
    _items.removeWhere((item) => item.id == id);
  }

  @override
  Future<List<User>> getAllFromCache() async => List.unmodifiable(_items);

  @override
  Future<void> updateCache(List<User> items) async {
    _items.clear();
    _items.addAll(items);
  }
}

/// Fake implementation of PostRepository for testing.
///
/// Uses an in-memory list to simulate repository operations.
class FakePostRepository implements PostRepository {
  final List<Post> _items = [];

  @override
  Future<List<Post>> getAll({
    int page = 1,
    int pageSize = 20,
    Map<String, dynamic>? filters,
    String? sortBy,
    String? sortOrder,
  }) async {
    return List.unmodifiable(_items);
  }

  @override
  Future<Post> getById(String id) async {
    return _items.firstWhere((item) => item.id == id);
  }

  @override
  Future<Post> create(Post item) async {
    _items.add(item);
    return item;
  }

  @override
  Future<Post> update(Post item) async {
    final index = _items.indexWhere((i) => i.id == item.id);
    if (index >= 0) _items[index] = item;
    return item;
  }

  @override
  Future<void> delete(String id) async {
    _items.removeWhere((item) => item.id == id);
  }

  @override
  Future<List<Post>> getAllFromCache() async => List.unmodifiable(_items);

  @override
  Future<void> updateCache(List<Post> items) async {
    _items.clear();
    _items.addAll(items);
  }
}

/// Fake implementation of CommentRepository for testing.
///
/// Uses an in-memory list to simulate repository operations.
class FakeCommentRepository implements CommentRepository {
  final List<Comment> _items = [];

  @override
  Future<List<Comment>> getAll({
    int page = 1,
    int pageSize = 20,
    Map<String, dynamic>? filters,
    String? sortBy,
    String? sortOrder,
  }) async {
    return List.unmodifiable(_items);
  }

  @override
  Future<Comment> getById(String id) async {
    return _items.firstWhere((item) => item.id == id);
  }

  @override
  Future<Comment> create(Comment item) async {
    _items.add(item);
    return item;
  }

  @override
  Future<Comment> update(Comment item) async {
    final index = _items.indexWhere((i) => i.id == item.id);
    if (index >= 0) _items[index] = item;
    return item;
  }

  @override
  Future<void> delete(String id) async {
    _items.removeWhere((item) => item.id == id);
  }

  @override
  Future<List<Comment>> getAllFromCache() async => List.unmodifiable(_items);

  @override
  Future<void> updateCache(List<Comment> items) async {
    _items.clear();
    _items.addAll(items);
  }
}

