// Generated by Schnitzel Framework v0.1.0
// DO NOT EDIT - This file is auto-generated
// Generated at: 2025-12-06T13:01:51.516283
// Source: schema.schnitzel.yaml

import 'package:mockito/annotations.dart';
import 'package:my_blog/repositories/repositories.dart';

@GenerateMocks([UserRepository, PostRepository, CommentRepository])
void main() {}
