// Generated by Schnitzel Framework
// DO NOT EDIT - This file is auto-generated
// Generated at: 2025-12-04T16:53:26.831920
// Source: schema.schnitzel.yaml

// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';

part 'models.freezed.dart';
part 'models.g.dart';

/// A user in the system
@freezed
abstract class User with _$User {
  const factory User({
    required String id,
    required String name,
    required String email,
    String? bio,
    @JsonKey(name: 'is_active') @Default(true) bool isActive,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    List<Post>? posts,
    List<Comment>? comments,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}

/// A blog post
@freezed
abstract class Post with _$Post {
  const factory Post({
    required String id,
    required String title,
    required String content,
    @JsonKey(name: 'author_id') required String authorId,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    User? author,
    List<Comment>? comments,
  }) = _Post;

  factory Post.fromJson(Map<String, dynamic> json) => _$PostFromJson(json);
}

/// A comment on a post
@freezed
abstract class Comment with _$Comment {
  const factory Comment({
    required String id,
    required String content,
    @JsonKey(name: 'author_id') required String authorId,
    @JsonKey(name: 'post_id') required String postId,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    User? author,
    Post? post,
  }) = _Comment;

  factory Comment.fromJson(Map<String, dynamic> json) => _$CommentFromJson(json);
}
