// Generated by Schnitzel Framework
// DO NOT EDIT - This file is auto-generated
// Generated at: 2025-12-04T12:55:43.356072
// Source: force_watch.yaml

// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';

part 'models.freezed.dart';
part 'models.g.dart';

@freezed
abstract class User with _$User {
  const factory User({
    required String id,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}
