// Generated by Schnitzel Framework
// DO NOT EDIT - This file is auto-generated
// Generated at: 2025-12-03T23:20:33.171228
// Source: force_watch.yaml

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';

part 'models.freezed.dart';
part 'models.g.dart';

@freezed
class User with _$User {
  const factory User({
    required String id,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}
