// Generated by Schnitzel Framework v0.1.0
// DO NOT EDIT - This file is auto-generated
// Generated at: 2025-12-06T13:01:51.515978
// Source: schema.schnitzel.yaml

import 'package:faker/faker.dart';
import 'package:my_blog_shared/models/models.dart';

/// A user in the system
///
/// Example usage:
/// ```dart
/// final user = UserFactory.create();
/// final custom = UserFactory.create(
///   id: 'custom_value',
/// );
/// final list = UserFactory.createList(10);
/// ```
class UserFactory {
  static final _faker = Faker();

  static User create({
    String? id,
    String? name,
    String? email,
    String? bio,
    bool? isActive,
    DateTime? createdAt,
  }) {
    return User(
      id: id ?? _faker.guid.guid(),
      name: name ?? _faker.person.name(),
      email: email ?? _faker.internet.email(),
      bio: bio ?? _faker.lorem.sentence(),
      isActive: isActive ?? _faker.randomGenerator.boolean(),
      createdAt: createdAt ?? DateTime.now(),
    );
  }

  static List<User> createList(int count) {
    return List.generate(count, (_) => create());
  }
}

/// A blog post
///
/// Example usage:
/// ```dart
/// final post = PostFactory.create();
/// final custom = PostFactory.create(
///   id: 'custom_value',
/// );
/// final list = PostFactory.createList(10);
/// ```
class PostFactory {
  static final _faker = Faker();

  static Post create({
    String? id,
    String? title,
    String? content,
    String? authorId,
    DateTime? createdAt,
  }) {
    return Post(
      id: id ?? _faker.guid.guid(),
      title: title ?? _faker.lorem.word(),
      content: content ?? _faker.lorem.sentence(),
      authorId: authorId ?? _faker.guid.guid(),
      createdAt: createdAt ?? DateTime.now(),
    );
  }

  static List<Post> createList(int count) {
    return List.generate(count, (_) => create());
  }
}

/// A comment on a post
///
/// Example usage:
/// ```dart
/// final comment = CommentFactory.create();
/// final custom = CommentFactory.create(
///   id: 'custom_value',
/// );
/// final list = CommentFactory.createList(10);
/// ```
class CommentFactory {
  static final _faker = Faker();

  static Comment create({
    String? id,
    String? content,
    String? authorId,
    String? postId,
    DateTime? createdAt,
  }) {
    return Comment(
      id: id ?? _faker.guid.guid(),
      content: content ?? _faker.lorem.sentence(),
      authorId: authorId ?? _faker.guid.guid(),
      postId: postId ?? _faker.guid.guid(),
      createdAt: createdAt ?? DateTime.now(),
    );
  }

  static List<Comment> createList(int count) {
    return List.generate(count, (_) => create());
  }
}
