# Generated by Schnitzel Framework v0.1.0
# DO NOT EDIT - This file is auto-generated
# Generated at: 2025-12-06T13:01:51.507203
# Source: schema.schnitzel.yaml

from unittest.mock import MagicMock, AsyncMock
import pytest
from app.models import Comment, Post, User


@pytest.fixture
def mock_user_repository():
    """Mock UserRepository for testing."""
    repo = MagicMock()
    repo.get_all = AsyncMock(return_value=[])
    repo.get_by_id = AsyncMock(return_value=None)
    repo.create = AsyncMock(side_effect=lambda item: item)
    repo.update = AsyncMock(side_effect=lambda item: item)
    repo.delete = AsyncMock(return_value=None)
    return repo

@pytest.fixture
def sample_user():
    """Sample User instance for testing."""
    return User(
        id="test-uuid-0",
        name="Name 0",
        email="user0@example.com",
        bio="test-bio-0",
        is_active=True,
        created_at="2024-01-01T00:00:00"
    )

@pytest.fixture
def sample_users():
    """List of sample User instances."""
    return [
        User(id="test-uuid-0", name="Name 0", email="user0@example.com", bio="test-bio-0", is_active=True, created_at="2024-01-01T00:00:00"),
        User(id="test-uuid-1", name="Name 1", email="user1@example.com", bio="test-bio-1", is_active=True, created_at="2024-01-01T00:00:00"),
        User(id="test-uuid-2", name="Name 2", email="user2@example.com", bio="test-bio-2", is_active=True, created_at="2024-01-01T00:00:00")
    ]

@pytest.fixture
def mock_post_repository():
    """Mock PostRepository for testing."""
    repo = MagicMock()
    repo.get_all = AsyncMock(return_value=[])
    repo.get_by_id = AsyncMock(return_value=None)
    repo.create = AsyncMock(side_effect=lambda item: item)
    repo.update = AsyncMock(side_effect=lambda item: item)
    repo.delete = AsyncMock(return_value=None)
    return repo

@pytest.fixture
def sample_post():
    """Sample Post instance for testing."""
    return Post(
        id="test-uuid-0",
        title="test-title-0",
        content="test-content-0",
        author_id="uuid-0",
        created_at="2024-01-01T00:00:00"
    )

@pytest.fixture
def sample_posts():
    """List of sample Post instances."""
    return [
        Post(id="test-uuid-0", title="test-title-0", content="test-content-0", author_id="uuid-0", created_at="2024-01-01T00:00:00"),
        Post(id="test-uuid-1", title="test-title-1", content="test-content-1", author_id="uuid-1", created_at="2024-01-01T00:00:00"),
        Post(id="test-uuid-2", title="test-title-2", content="test-content-2", author_id="uuid-2", created_at="2024-01-01T00:00:00")
    ]

@pytest.fixture
def mock_comment_repository():
    """Mock CommentRepository for testing."""
    repo = MagicMock()
    repo.get_all = AsyncMock(return_value=[])
    repo.get_by_id = AsyncMock(return_value=None)
    repo.create = AsyncMock(side_effect=lambda item: item)
    repo.update = AsyncMock(side_effect=lambda item: item)
    repo.delete = AsyncMock(return_value=None)
    return repo

@pytest.fixture
def sample_comment():
    """Sample Comment instance for testing."""
    return Comment(
        id="test-uuid-0",
        content="test-content-0",
        author_id="uuid-0",
        post_id="uuid-0",
        created_at="2024-01-01T00:00:00"
    )

@pytest.fixture
def sample_comments():
    """List of sample Comment instances."""
    return [
        Comment(id="test-uuid-0", content="test-content-0", author_id="uuid-0", post_id="uuid-0", created_at="2024-01-01T00:00:00"),
        Comment(id="test-uuid-1", content="test-content-1", author_id="uuid-1", post_id="uuid-1", created_at="2024-01-01T00:00:00"),
        Comment(id="test-uuid-2", content="test-content-2", author_id="uuid-2", post_id="uuid-2", created_at="2024-01-01T00:00:00")
    ]
