# Generated by Schnitzel Framework v0.1.0
# DO NOT EDIT - This file is auto-generated
# Generated at: 2025-12-06T13:01:51.506889
# Source: schema.schnitzel.yaml

from app.models import User, Post, Comment
from datetime import datetime
from uuid import uuid4
import factory


class UserFactory(factory.Factory):
    class Meta:
        model = User

    id = factory.LazyFunction(lambda: str(uuid4()))
    name = factory.Faker('name')
    email = factory.Sequence(lambda n: f'user{n}@example.com')
    bio = factory.Faker('paragraph')
    is_active = factory.Faker('boolean')
    created_at = factory.LazyFunction(datetime.utcnow)



class PostFactory(factory.Factory):
    class Meta:
        model = Post

    id = factory.LazyFunction(lambda: str(uuid4()))
    title = factory.Faker('word')
    content = factory.Faker('paragraph')
    author_id = factory.LazyFunction(lambda: str(uuid4()))
    created_at = factory.LazyFunction(datetime.utcnow)

    author = factory.SubFactory(UserFactory)


class CommentFactory(factory.Factory):
    class Meta:
        model = Comment

    id = factory.LazyFunction(lambda: str(uuid4()))
    content = factory.Faker('paragraph')
    author_id = factory.LazyFunction(lambda: str(uuid4()))
    post_id = factory.LazyFunction(lambda: str(uuid4()))
    created_at = factory.LazyFunction(datetime.utcnow)

    author = factory.SubFactory(UserFactory)
    post = factory.SubFactory(PostFactory)
