"""FastAPI application entry point for Schnitzel backend.

Generated by Schnitzel 0.1.0
Source: schema.schnitzel.yaml
Generated at: 2025-12-05T18:45:40.017796
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .database import init_db, close_db
from .settings import settings


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan handler for startup and shutdown events."""
    # Startup: Initialize database tables
    await init_db()
    yield
    # Shutdown: Close database connections
    await close_db()


app = FastAPI(
    title="Schnitzel Backend",
    description="Schema-driven FastAPI backend generated by Schnitzel",
    version="0.1.0",
    lifespan=lifespan,
)

# Configure CORS from settings
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=settings.cors_allow_credentials,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
async def root():
    """Root endpoint."""
    return {
        "message": "Welcome to Schnitzel Backend",
        "version": "0.1.0",
        "status": "running"
    }


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "service": settings.app_name,
    }


# Import and register generated routes
from .generated.routes import router as generated_router
app.include_router(generated_router, prefix=settings.api_prefix)