# Generated by Schnitzel Framework v0.1.0
# DO NOT EDIT - This file is auto-generated
# Generated at: 2025-12-05T18:45:40.015002
# Source: schema.schnitzel.yaml



from datetime import datetime
from pydantic import BaseModel, Field
from typing import Literal
from uuid import UUID


class Player(BaseModel):
    """A player in the Prompt Duel game"""

    # Fields
    id: UUID
    username: str = Field(max_length=20)
    display_name: str = Field(max_length=50)
    email: str
    avatar_url: str | None = None
    elo_rating: int = 1000
    total_wins: int = 0
    total_losses: int = 0
    total_draws: int = 0
    is_banned: bool = False
    created_at: datetime
    updated_at: datetime

class Match(BaseModel):
    """A competitive match between two players"""

    # Fields
    id: UUID
    player1_id: UUID
    player2_id: UUID | None = None
    status: Literal["waiting", "in_progress", "completed", "cancelled"] = "waiting"
    winner_id: UUID | None = None
    mode: Literal["ranked", "casual", "practice"] = "casual"
    max_rounds: int = 3
    current_round: int = 0
    player1_score: int = 0
    player2_score: int = 0
    started_at: datetime | None = None
    ended_at: datetime | None = None
    created_at: datetime

class Round(BaseModel):
    """A single round within a match"""

    # Fields
    id: UUID
    match_id: UUID
    round_number: int
    puzzle: str
    player1_prompt: str | None = None
    player2_prompt: str | None = None
    player1_result: str | None = None
    player2_result: str | None = None
    winner_id: UUID | None = None
    arbiter_reasoning: str | None = None
    time_limit_seconds: int = 60
    created_at: datetime

class Prompt(BaseModel):
    """A submitted prompt in a round"""

    # Fields
    id: UUID
    round_id: UUID
    player_id: UUID
    content: str = Field(max_length=500)
    token_count: int
    execution_result: str | None = None
    score: float | None = None
    submitted_at: datetime

class Leaderboard(BaseModel):
    """Season leaderboard entry"""

    # Fields
    id: UUID
    player_id: UUID
    season: str
    rank: int
    elo_rating: int
    wins: int = 0
    losses: int = 0
    win_streak: int = 0
    best_streak: int = 0
    updated_at: datetime
