// Generated by Schnitzel Framework v0.1.0
// DO NOT EDIT - This file is auto-generated
// Generated at: 2025-12-06T12:21:19.517739
// Source: schema.schnitzel.yaml

import 'package:flutter_test/flutter_test.dart';
import 'package:my_blog/main.dart';

void main() {
  testWidgets('App loads home screen smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(const MyBlogApp());
    await tester.pumpAndSettle();

    // Verify that we see the home screen title
    expect(find.text('My Blog'), findsWidgets);
  });
}
