"""Python Dockerfile generator for Schnitzel schemas.

Generates a Dockerfile for running the FastAPI backend with:
- Python 3.11 slim base image
- Non-root user for security
- Optimized layer caching
- uvicorn server configuration
"""

from datetime import datetime
from pathlib import Path
from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema


class DockerfileGenerator:
    """Generates Dockerfile for Python FastAPI backend."""

    def generate(self, schema: SchnitzelSchema, project_name: str = "schnitzel") -> str:
        """
        Generate Dockerfile content.

        Args:
            schema: The Schnitzel schema
            project_name: Name of the project

        Returns:
            Generated Dockerfile content as a string
        """
        dockerfile = f'''# Generated by Schnitzel Framework v{__version__}
# Generated at: {datetime.now().isoformat()}

FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update \\
    && apt-get install -y --no-install-recommends \\
        build-essential \\
        libpq-dev \\
    && rm -rf /var/lib/apt/lists/*

# Create non-root user for security
RUN addgroup --system app && adduser --system --group app

# Copy requirements first for layer caching
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade pip \\
    && pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Change ownership to non-root user
RUN chown -R app:app /app

# Switch to non-root user
USER app

# Expose port
EXPOSE 8000

# Run uvicorn server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
'''
        return dockerfile

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        project_name: str = "schnitzel",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate Dockerfile and write it to a file.

        Args:
            schema: The Schnitzel schema
            output_dir: Directory where Dockerfile should be written
            project_name: Name of the project
            dry_run: If True, return file info without writing

        Returns:
            Tuple of (Path to Dockerfile, size in bytes)
        """
        output_path = Path(output_dir)

        if not dry_run:
            output_path.mkdir(parents=True, exist_ok=True)

        code = self.generate(schema, project_name=project_name)
        output_file = output_path / "Dockerfile"

        if not dry_run:
            output_file.write_text(code, encoding='utf-8')

        size = len(code.encode('utf-8'))
        return output_file, size

    def generate_dockerignore(self) -> str:
        """
        Generate .dockerignore content.

        Returns:
            Generated .dockerignore content
        """
        return '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
.env
.venv
env/
venv/
ENV/

# IDE
.idea/
.vscode/
*.swp
*.swo

# Testing
.pytest_cache/
.coverage
htmlcov/

# Git
.git/
.gitignore

# Docker
Dockerfile
docker-compose*.yml
.docker/

# Documentation
docs/
*.md

# Local development
.env.local
.env.*.local
'''

    def generate_dockerignore_to_file(
        self,
        output_dir: str | Path,
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate .dockerignore and write it to a file.

        Args:
            output_dir: Directory where .dockerignore should be written
            dry_run: If True, return file info without writing

        Returns:
            Tuple of (Path to .dockerignore, size in bytes)
        """
        output_path = Path(output_dir)

        if not dry_run:
            output_path.mkdir(parents=True, exist_ok=True)

        content = self.generate_dockerignore()
        output_file = output_path / ".dockerignore"

        if not dry_run:
            output_file.write_text(content, encoding='utf-8')

        size = len(content.encode('utf-8'))
        return output_file, size
