"""Python database.py generator for Schnitzel schemas.

Generates async SQLAlchemy database configuration with:
- Async engine and session management
- Dependency injection for FastAPI
- Proper connection pooling
"""

from datetime import datetime
from pathlib import Path
from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema


class DatabaseGenerator:
    """Generates database.py with async SQLAlchemy configuration."""

    def generate(self, schema: SchnitzelSchema) -> str:
        """
        Generate database.py content with async SQLAlchemy.

        Args:
            schema: The Schnitzel schema

        Returns:
            Generated Python code as a string
        """
        code = f'''"""Async SQLAlchemy database configuration.

Generated by Schnitzel Framework v{__version__}
Generated at: {datetime.now().isoformat()}

Provides async database session management for FastAPI with:
- Async engine with connection pooling
- Session factory for dependency injection
- get_db dependency for route handlers
"""

from collections.abc import AsyncGenerator
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase

from .settings import settings


# Create async database engine
engine = create_async_engine(
    settings.database_url,
    echo=settings.debug,
    pool_pre_ping=True,  # Enable connection health checks
    pool_size=5,
    max_overflow=10,
)

# Create async session factory
async_session_maker = async_sessionmaker(
    engine,
    class_=AsyncSession,
    expire_on_commit=False,
    autocommit=False,
    autoflush=False,
)


class Base(DeclarativeBase):
    """Base class for SQLAlchemy ORM models."""
    pass


async def get_db() -> AsyncGenerator[AsyncSession, None]:
    """
    FastAPI dependency that provides a database session.

    Yields an async session and ensures it's closed after the request.

    Usage:
        @router.get("/items")
        async def get_items(db: AsyncSession = Depends(get_db)):
            result = await db.execute(select(Item))
            return result.scalars().all()
    """
    async with async_session_maker() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise
        finally:
            await session.close()


async def init_db() -> None:
    """
    Initialize database tables.

    Creates all tables defined in ORM models that inherit from Base.
    Call this on application startup.
    """
    async with engine.begin() as conn:
        # Import ORM models to ensure they're registered with Base
        from .generated.orm import Base as ORMBase
        await conn.run_sync(ORMBase.metadata.create_all)


async def close_db() -> None:
    """
    Close database connections.

    Disposes of the connection pool. Call this on application shutdown.
    """
    await engine.dispose()
'''
        return code

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate database.py and write it to a file.

        Args:
            schema: The Schnitzel schema
            output_dir: Directory where database.py should be written
            dry_run: If True, return file info without writing

        Returns:
            Tuple of (Path to database.py, size in bytes)
        """
        output_path = Path(output_dir)

        if not dry_run:
            output_path.mkdir(parents=True, exist_ok=True)

        code = self.generate(schema)
        output_file = output_path / "database.py"

        if not dry_run:
            output_file.write_text(code, encoding='utf-8')

        size = len(code.encode('utf-8'))
        return output_file, size
