"""Python event publisher generator for Schnitzel schemas.

Generates event publishing infrastructure with Redis Pub/Sub and WebSocket support.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List
from jinja2 import Environment, PackageLoader, select_autoescape

from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema, PYTHON_TYPE_MAP
from schnitzel.generators.validation_utils import validate_channels, validate_payload_types


class EventPublisherGenerator:
    """Generates event publisher infrastructure from Schnitzel schemas."""

    def __init__(self):
        """Initialize the event publisher generator."""
        self.env = Environment(
            loader=PackageLoader('schnitzel', 'templates/python'),
            autoescape=select_autoescape(),
        )

    def generate(self, schema: SchnitzelSchema) -> str:
        """
        Generate event publisher infrastructure from a schema.

        Args:
            schema: The Schnitzel schema to generate event publishers from

        Returns:
            Generated Python code as a string
        """
        # Check if schema has events
        if not schema.events or not isinstance(schema.events, dict):
            return self._generate_empty_events()

        # Parse events and prepare template data
        events_data = []
        needs_uuid = False
        needs_decimal = False
        for event_name, event_def in schema.events.items():
            # Handle both dict and EventConfig objects
            event_info = self._parse_event(event_name, event_def)
            events_data.append(event_info)

            # Check if any payload field uses UUID or Decimal
            for field_info in event_info['payload_fields'].values():
                if 'UUID' in field_info['python_type']:
                    needs_uuid = True
                if 'Decimal' in field_info['python_type']:
                    needs_decimal = True

        # Load and render template
        template = self.env.get_template("events.py.j2")
        rendered = template.render(events=events_data, needs_uuid=needs_uuid, needs_decimal=needs_decimal)
        return rendered

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate event publisher infrastructure and write it to a file.

        Creates the output directory if it doesn't exist, adds a header comment with
        generation metadata, and writes the events code to 'events.py' in the specified directory.

        Args:
            schema: The Schnitzel schema to generate event publishers from
            output_dir: Directory where events.py should be written (can be string or Path)
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            Tuple of (Path object pointing to events.py file, size in bytes)

        Example:
            >>> generator = EventPublisherGenerator()
            >>> output_path, size = generator.generate_to_file(schema, "backend/app/generated")
            >>> print(f"Events written to: {output_path} ({size} bytes)")
        """
        # Convert to Path object
        output_path = Path(output_dir)

        # Generate the event publisher code
        events_code = self.generate(schema)

        # Build header comment
        timestamp = datetime.now().isoformat()
        header = f"""# Generated by Schnitzel Framework v{__version__}
# DO NOT EDIT - This file is auto-generated
# Generated at: {timestamp}
# Source: {schema_source}

"""

        # Combine header with generated code
        full_code = header + events_code

        # Calculate file path and size
        events_file = output_path / "events.py"
        file_size = len(full_code.encode("utf-8"))

        # If dry-run, return without writing
        if dry_run:
            return events_file, file_size

        # Create directory if it doesn't exist
        output_path.mkdir(parents=True, exist_ok=True)

        # Warn if file already exists
        if events_file.exists():
            print(f"Warning: Overwriting existing file: {events_file}")

        events_file.write_text(full_code, encoding="utf-8")

        return events_file, file_size

    def _generate_empty_events(self) -> str:
        """Generate a minimal events file when no events are defined."""
        return '''"""Event publisher infrastructure (no events defined)."""

import logging

logger = logging.getLogger(__name__)


class EventPublisher:
    """Event publisher with support for multiple channels."""

    def __init__(self, redis_client=None, websocket_manager=None):
        """Initialize the event publisher.

        Args:
            redis_client: Redis client for pub/sub (optional)
            websocket_manager: WebSocket connection manager (optional)
        """
        self.redis_client = redis_client
        self.websocket_manager = websocket_manager
        logger.info("EventPublisher initialized (no events configured)")
'''

    def _parse_event(self, event_name: str, event_def: Any) -> Dict[str, Any]:
        """Parse an event definition into template data.

        Args:
            event_name: Name of the event (e.g., "order.placed")
            event_def: Event definition from schema (dict or EventConfig)

        Returns:
            Dictionary with event information for template rendering

        Raises:
            ValueError: If validation fails
        """
        # Handle EventConfig objects
        from schnitzel.schema.models import EventConfig
        if isinstance(event_def, EventConfig):
            payload_dict = event_def.payload
            channels = event_def.channels
            description = event_def.description or ""
        elif isinstance(event_def, dict):
            payload_dict = event_def.get("payload", {})
            channels = event_def.get("channels", [])
            description = event_def.get("description", "")
        else:
            # Fallback for unexpected types
            payload_dict = {}
            channels = []
            description = ""

        # Validate channels (F97)
        if isinstance(channels, str):
            channels = [channels]
        try:
            validate_channels(channels)
        except ValueError as e:
            raise ValueError(f"Event '{event_name}': {e}") from e

        # Validate payload field types (F101)
        try:
            validate_payload_types(payload_dict)
        except ValueError as e:
            raise ValueError(f"Event '{event_name}': {e}") from e

        # Generate class name from event name: order.placed -> OrderPlacedPayload
        payload_class_name = self._event_name_to_class_name(event_name) + "Payload"

        # Generate method name: order.placed -> publish_order_placed
        method_name = event_name.replace(".", "_")

        # Parse payload fields
        payload_fields = {}
        if isinstance(payload_dict, dict):
            for field_name, field_def in payload_dict.items():
                # Handle both string types (e.g., "uuid") and dict definitions (e.g., {type: "uuid", optional: true})
                if isinstance(field_def, dict):
                    field_type = field_def.get("type", "string")
                    optional = field_def.get("optional", False)
                elif isinstance(field_def, str):
                    # Simple string type like "uuid", "string", "list<uuid>"
                    field_type = field_def
                    optional = False
                else:
                    # Fallback for unexpected types
                    field_type = "string"
                    optional = False

                python_type = self._get_python_type(field_type)

                # Add optional type annotation
                if optional:
                    python_type = f"{python_type} | None = None"

                payload_fields[field_name] = {
                    "python_type": python_type,
                    "type": field_type,
                    "optional": optional,
                }

        # Ensure channels is a list
        if isinstance(channels, str):
            channels = [channels]

        return {
            "name": event_name,
            "description": description,
            "payload_class_name": payload_class_name,
            "method_name": method_name,
            "payload_fields": payload_fields,
            "channels": channels,
            "channels_repr": repr(channels),  # Python list representation
        }

    def _event_name_to_class_name(self, event_name: str) -> str:
        """Convert event name to PascalCase class name.

        Args:
            event_name: Event name in dot.notation (e.g., "order.placed")

        Returns:
            PascalCase class name (e.g., "OrderPlaced")

        Examples:
            order.placed -> OrderPlaced
            payment.failed -> PaymentFailed
            user.profile.updated -> UserProfileUpdated
        """
        # Split by dots and underscores, capitalize each part
        parts = event_name.replace(".", "_").split("_")
        return "".join(part.capitalize() for part in parts)

    def _get_python_type(self, schema_type: str) -> str:
        """
        Map schema type to Python type.

        Args:
            schema_type: Type from schema (e.g., "string", "int", "uuid")

        Returns:
            Python type string (e.g., "str", "int", "UUID")
        """
        schema_type_lower = schema_type.lower()

        # Handle list types: list<string> -> list[str]
        if schema_type_lower.startswith("list<") and schema_type_lower.endswith(">"):
            inner_type = schema_type_lower[5:-1].strip()
            inner_python_type = PYTHON_TYPE_MAP.get(inner_type, inner_type)
            return f"list[{inner_python_type}]"

        # Handle standard types
        return PYTHON_TYPE_MAP.get(schema_type_lower, schema_type)
