"""Python FastAPI main.py generator for Schnitzel schemas.

Generates FastAPI application entry point with CORS middleware configured
for development. The generated main.py includes:
- FastAPI app initialization
- CORS middleware for cross-origin requests
- Root and health check endpoints
- Generated routes integration
"""

from datetime import datetime
from pathlib import Path
from jinja2 import Environment, FileSystemLoader, select_autoescape
from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema


class FastAPIMainGenerator:
    """Generates FastAPI main.py entry point from Schnitzel schemas."""

    def __init__(self):
        """Initialize the Python main.py generator."""
        # Set up Jinja2 environment
        template_dir = Path(__file__).parent.parent.parent / "templates" / "python"
        self.env = Environment(
            loader=FileSystemLoader(str(template_dir)),
            autoescape=select_autoescape(['html', 'xml']),
            trim_blocks=True,
            lstrip_blocks=True,
        )

    def generate(self, schema: SchnitzelSchema, app_name: str = "schnitzel-backend") -> str:
        """
        Generate Python FastAPI main.py from a schema.

        Args:
            schema: The Schnitzel schema to generate main.py from
            app_name: Name of the application (default: "schnitzel-backend")

        Returns:
            Generated Python code as a string
        """
        template = self.env.get_template('main.py.j2')

        # Prepare template context
        # Get metadata safely
        metadata = getattr(schema, 'metadata', None) or {}

        context = {
            'schnitzel_version': __version__,
            'schema_source': 'schema.schnitzel.yaml',
            'timestamp': datetime.now().isoformat(),
            'app_title': metadata.get('title', 'Schnitzel Backend') if isinstance(metadata, dict) else 'Schnitzel Backend',
            'app_description': metadata.get('description', 'Schema-driven FastAPI backend generated by Schnitzel') if isinstance(metadata, dict) else 'Schema-driven FastAPI backend generated by Schnitzel',
            'app_version': metadata.get('version', '0.1.0') if isinstance(metadata, dict) else '0.1.0',
            'app_name': app_name,
        }

        return template.render(**context)

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        app_name: str = "schnitzel-backend",
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate Python FastAPI main.py and write it to a file.

        Creates the output directory if it doesn't exist, adds a header comment with
        generation metadata, and writes the main.py to the specified directory.

        Args:
            schema: The Schnitzel schema to generate main.py from
            output_dir: Directory where main.py should be written (can be string or Path)
            app_name: Name of the application (default: "schnitzel-backend")
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            Tuple of (Path object pointing to main.py file, size in bytes)

        Raises:
            OSError: If directory creation or file writing fails
        """
        output_path = Path(output_dir)

        # Create output directory if it doesn't exist
        if not dry_run:
            output_path.mkdir(parents=True, exist_ok=True)

        # Generate code
        code = self.generate(schema, app_name=app_name)

        # Construct output file path
        output_file = output_path / "main.py"

        if not dry_run:
            # Write to file
            output_file.write_text(code, encoding='utf-8')

        # Return file path and size
        size = len(code.encode('utf-8'))
        return output_file, size


class PythonMainGenerator(FastAPIMainGenerator):
    """Alias for FastAPIMainGenerator for consistency with naming conventions."""
    pass
