"""Python requirements.txt generator for Schnitzel schemas.

Generates requirements.txt with all dependencies needed for a runnable
FastAPI backend with async SQLAlchemy support.
"""

from datetime import datetime
from pathlib import Path
from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema


class RequirementsGenerator:
    """Generates requirements.txt for Python backend."""

    def generate(self, schema: SchnitzelSchema) -> str:
        """
        Generate requirements.txt content.

        Args:
            schema: The Schnitzel schema (used for future feature detection)

        Returns:
            Generated requirements.txt content as a string
        """
        requirements = [
            "# Generated by Schnitzel Framework",
            f"# Version: {__version__}",
            f"# Generated at: {datetime.now().isoformat()}",
            "",
            "# FastAPI framework",
            "fastapi>=0.109.0",
            "uvicorn[standard]>=0.27.0",
            "",
            "# Database (async SQLAlchemy with PostgreSQL)",
            "sqlalchemy[asyncio]>=2.0.0",
            "asyncpg>=0.29.0",
            "",
            "# Data validation and settings",
            "pydantic>=2.0.0",
            "pydantic-settings>=2.0.0",
            "",
            "# Utilities",
            "python-multipart>=0.0.6",  # For form data
            "",
            "# Testing",
            "pytest>=8.0.0",
            "pytest-asyncio>=0.23.0",
            "pytest-mock>=3.14.0",
            "factory-boy>=3.3.0",  # Test factories
        ]

        return "\n".join(requirements) + "\n"

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate requirements.txt and write it to a file.

        Args:
            schema: The Schnitzel schema
            output_dir: Directory where requirements.txt should be written
            dry_run: If True, return file info without writing

        Returns:
            Tuple of (Path to requirements.txt, size in bytes)
        """
        output_path = Path(output_dir)

        if not dry_run:
            output_path.mkdir(parents=True, exist_ok=True)

        code = self.generate(schema)
        output_file = output_path / "requirements.txt"

        if not dry_run:
            output_file.write_text(code, encoding='utf-8')

        size = len(code.encode('utf-8'))
        return output_file, size
