"""Python FastAPI route generator for Schnitzel schemas.

Generates FastAPI routes with proper HTTP method decorators, request/response types,
and Pydantic model integration.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Set
from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema, PYTHON_TYPE_MAP


class FastAPIRouteGenerator:
    """Generates FastAPI routes from Schnitzel schemas."""

    def __init__(self):
        """Initialize the Python route generator."""
        self.imports: Set[str] = set()

    def generate(self, schema: SchnitzelSchema) -> str:
        """
        Generate Python FastAPI routes from a schema.

        Args:
            schema: The Schnitzel schema to generate routes from

        Returns:
            Generated Python code as a string
        """
        self.imports = set()
        self.model_imports = set()
        self.has_rate_limiting = False

        # Check if schema has endpoints
        if not schema.endpoints:
            return self._generate_empty_routes()

        # Parse endpoints and generate routes
        route_functions = []
        for path, methods in schema.endpoints.items():
            # Handle path parameters (e.g., /users/{id})
            path_params = self._extract_path_params(path)

            # Get shared parameters for this path
            shared_params = methods.get("params", {}) if isinstance(methods, dict) else {}

            # Generate routes for each HTTP method
            for method_name, endpoint_def in methods.items():
                if method_name == "params":
                    continue  # Skip shared params

                if isinstance(endpoint_def, dict):
                    route_code = self._generate_route_function(
                        path, method_name, endpoint_def, path_params, shared_params
                    )
                    route_functions.append(route_code)

        # Add rate limiting helper if any endpoint uses rate limiting
        rate_limit_helper = ""
        if self.has_rate_limiting:
            rate_limit_helper = self._generate_rate_limit_helper()

        # Collect imports (after potentially adding rate limiting imports)
        self._collect_imports()

        # Build final code with model imports
        imports_code = "\n".join(sorted(self.imports))

        # Add model imports if any
        # Use relative import from same directory (routes.py and models.py are both in backend/app/)
        if self.model_imports:
            model_imports_str = ", ".join(sorted(self.model_imports))
            imports_code += f"\nfrom .models import {model_imports_str}"  # noqa: E402

        routes_code = "\n\n".join(route_functions)

        # Add section comment if we have routes
        routes_header = "\n\n# =============================================================================\n# Route Endpoints\n# =============================================================================\n\n" if route_functions else "\n\n"

        return f"{imports_code}\n\n\nrouter = APIRouter(){routes_header}{rate_limit_helper}{routes_code}\n"

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate Python FastAPI routes and write them to a file.

        Creates the output directory if it doesn't exist, adds a header comment with
        generation metadata, and writes the routes to 'routes.py' in the specified directory.

        Args:
            schema: The Schnitzel schema to generate routes from
            output_dir: Directory where routes.py should be written (can be string or Path)
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            Tuple of (Path object pointing to routes.py file, size in bytes)

        Example:
            >>> generator = PythonRouteGenerator()
            >>> output_path, size = generator.generate_to_file(schema, "backend/app/generated")
            >>> print(f"Routes written to: {output_path} ({size} bytes)")
        """
        # Convert to Path object
        output_path = Path(output_dir)

        # Generate the route code
        routes_code = self.generate(schema)

        # Build header comment
        timestamp = datetime.now().isoformat()
        header = f"""# Generated by Schnitzel Framework v{__version__}
# DO NOT EDIT - This file is auto-generated
# Generated at: {timestamp}
# Source: {schema_source}

"""

        # Combine header with generated code
        full_code = header + routes_code

        # Calculate file path and size
        routes_file = output_path / "routes.py"
        file_size = len(full_code.encode("utf-8"))

        # If dry-run, return without writing
        if dry_run:
            return routes_file, file_size

        # Create directory if it doesn't exist
        output_path.mkdir(parents=True, exist_ok=True)

        # Warn if file already exists
        if routes_file.exists():
            print(f"Warning: Overwriting existing file: {routes_file}")

        routes_file.write_text(full_code, encoding="utf-8")

        return routes_file, file_size

    def _generate_empty_routes(self) -> str:
        """Generate a minimal routes file when no endpoints are defined."""
        self.imports.add("from fastapi import APIRouter")
        imports_code = "\n".join(sorted(self.imports))
        return f"{imports_code}\n\n\nrouter = APIRouter()\n"

    def _extract_path_params(self, path: str) -> Dict[str, str]:
        """Extract path parameters from a route path.

        Args:
            path: Route path (e.g., "/users/{id}")

        Returns:
            Dictionary of parameter names to types (defaults to str)

        Example:
            >>> _extract_path_params("/users/{id}")
            {"id": "str"}
        """
        import re

        params = {}
        # Find all {param} patterns
        pattern = r"\{(\w+)\}"
        matches = re.findall(pattern, path)
        for param_name in matches:
            # Default to string, will be overridden by schema definition
            params[param_name] = "str"
        return params

    def _generate_route_function(
        self,
        path: str,
        method: str,
        endpoint_def: Dict[str, Any],
        path_params: Dict[str, str],
        shared_params: Dict[str, Any],
    ) -> str:
        """Generate a single route function.

        Args:
            path: API path (e.g., "/users")
            method: HTTP method (GET, POST, PUT, DELETE, etc.)
            endpoint_def: Endpoint definition from schema
            path_params: Extracted path parameters with types
            shared_params: Shared parameters for this path

        Returns:
            Generated route function code as string
        """
        method_lower = method.lower()
        function_name = endpoint_def.get("name", f"{method_lower}_{path.replace('/', '_').replace('{', '').replace('}', '')}")

        # Merge shared params with path params
        all_path_params = {**path_params}
        if shared_params:
            for param_name, param_def in shared_params.items():
                if param_name in all_path_params:
                    # Override default type with schema definition
                    all_path_params[param_name] = self._get_python_type(param_def.get("type", "string"))

        # Check if response headers are defined
        has_response_headers = self._has_response_headers(endpoint_def)

        # Build function parameters
        # We need to separate required and optional params to maintain proper ordering
        params = []
        required_params = []  # Path params, required query params, body
        optional_params = []  # Optional query params, auth dependency, response

        # Add WebSocket parameter for WebSocket endpoints (must be first)
        if method_lower == "ws":
            required_params.append("websocket: WebSocket")
            self.imports.add("from fastapi import WebSocket")

        # Add path parameters (always required)
        for param_name, param_type in all_path_params.items():
            # Get type from shared_params if available
            if shared_params and param_name in shared_params:
                param_def = shared_params[param_name]
                param_type = self._get_python_type(param_def.get("type", "string"))
            required_params.append(f"{param_name}: {param_type}")

        # Add Response parameter if headers are needed
        if has_response_headers:
            optional_params.append("response: Response")
            self.imports.add("from fastapi import Response")

        # Check if endpoint has pagination enabled
        has_pagination = endpoint_def.get("pagination", False)

        # Add query parameters (or pagination parameters if enabled)
        if has_pagination:
            # Add standard pagination parameters
            self.imports.add("from fastapi import Query")
            optional_params.append("page: int = Query(1, ge=1, description=\"Page number (1-indexed)\")")
            optional_params.append("per_page: int = Query(20, ge=1, le=100, description=\"Items per page\")")

        if "query" in endpoint_def:
            # Query parameters require Query() import
            self.imports.add("from fastapi import Query")

            for query_name, query_def in endpoint_def["query"].items():
                query_type = self._get_python_type(query_def.get("type", "string"))
                optional = query_def.get("optional", False)
                default = query_def.get("default")

                # Build Query() validation arguments
                query_args = []

                # Determine if required (no default and not optional)
                if not optional and default is None:
                    query_args.append("...")
                elif default is not None:
                    query_args.append(self._format_default(default))
                else:
                    query_args.append("None")

                # Add validation constraints if present
                if "min" in query_def:
                    if query_type in ["int", "float"]:
                        query_args.append(f"ge={query_def['min']}")

                if "max" in query_def:
                    if query_type in ["int", "float"]:
                        query_args.append(f"le={query_def['max']}")

                if "max_length" in query_def:
                    if query_type == "str":
                        query_args.append(f"max_length={query_def['max_length']}")

                # Add description if present
                if "description" in query_def:
                    desc = query_def["description"].replace('"', '\\"')
                    query_args.append(f'description="{desc}"')

                # Build the parameter with Query()
                query_call = f"Query({', '.join(query_args)})"

                if optional or default is not None:
                    # Optional parameters
                    optional_params.append(f"{query_name}: {query_type} | None = {query_call}")
                else:
                    # Required parameters (but Query() is a default, so treated as optional by Python)
                    optional_params.append(f"{query_name}: {query_type} = {query_call}")

        # Add request body for POST/PUT/PATCH (required param)
        if method_lower in ["post", "put", "patch"]:
            if "body" in endpoint_def:
                body_type = endpoint_def["body"]
                if isinstance(body_type, str):
                    # Check if this is a file upload type
                    body_type_lower = body_type.lower()
                    if body_type_lower in ["file", "upload", "uploadfile"]:
                        # File upload parameter using FastAPI's UploadFile
                        required_params.append("file: UploadFile = File(...)")
                        # Track that we need UploadFile and File imports
                        self.imports.add("from fastapi import File")
                        self.imports.add("from fastapi import UploadFile")
                    else:
                        # Reference to a Pydantic model
                        required_params.append(f"body: {body_type}")
                        # Track model import
                        self.model_imports.add(body_type)
                elif isinstance(body_type, dict):
                    # Check if dict specifies file/upload type
                    if "type" in body_type:
                        body_dict_type = body_type["type"].lower()
                        if body_dict_type in ["file", "upload", "uploadfile"]:
                            # File upload parameter using FastAPI's UploadFile
                            required_params.append("file: UploadFile = File(...)")
                            # Track that we need UploadFile and File imports
                            self.imports.add("from fastapi import File")
                            self.imports.add("from fastapi import UploadFile")
                        else:
                            # Inline body definition - use generic Body parameter
                            required_params.append("body: dict[str, Any]")
                            self.imports.add("from typing import Any")
                    else:
                        # Inline body definition - use generic Body parameter
                        required_params.append("body: dict[str, Any]")
                        self.imports.add("from typing import Any")

        # Add background tasks if required (optional param with default)
        if endpoint_def.get("background_task") is True:
            optional_params.append("background_tasks: BackgroundTasks")
            # Track that we need BackgroundTasks import
            self.imports.add("from fastapi import BackgroundTasks")

        # Add auth dependency if required (optional param with default)
        if endpoint_def.get("auth") == "required":
            # Check if roles are specified for role-based access control
            roles = endpoint_def.get("roles")
            if roles:
                # Generate role checking dependency
                # Convert roles list to string representation for Python code
                roles_str = str(roles)  # e.g., ['admin', 'moderator']
                optional_params.append(f"current_user: User = Depends(require_roles({roles_str}))")
                # Track that we need auth imports
                self.imports.add("from fastapi import Depends")
                self.imports.add("from ..auth import require_roles")
            else:
                # Standard auth without role checking
                optional_params.append("current_user: User = Depends(get_current_user)")
                # Track that we need auth imports
                self.imports.add("from fastapi import Depends")
                self.imports.add("from ..auth import get_current_user")
            # Track User model import
            self.model_imports.add("User")

        # Combine params: required first, then optional
        params = required_params + optional_params

        # Determine return type and status code from response
        return_type = "None"
        response_status_code = None
        if "response" in endpoint_def:
            responses = endpoint_def["response"]

            # Handle simple string response format (e.g., "User" or "User[]")
            if isinstance(responses, str):
                return_type = responses
                # Handle list type notation
                if return_type.endswith("[]"):
                    base_type = return_type[:-2]
                    return_type = f"list[{base_type}]"
                    if base_type and base_type[0].isupper():
                        self.model_imports.add(base_type)
                elif return_type and return_type[0].isupper():
                    self.model_imports.add(return_type)
            elif isinstance(responses, dict):
                # Look for successful response (200, 201, 202, 204)
                for status_code_check in [200, 201, 202, 204]:
                    if status_code_check in responses:
                        response_def = responses[status_code_check]
                        # Capture the status code that was found
                        response_status_code = status_code_check

                        if isinstance(response_def, dict) and "type" in response_def:
                            return_type = response_def["type"]

                            # Convert angle brackets to square brackets for Python generics
                            # PaginatedResponse<User> -> PaginatedResponse[User]
                            return_type = return_type.replace("<", "[").replace(">", "]")

                            # Track model import (handle generic types like PaginatedResponse[User])
                            # Extract the base type and any generic parameters
                            if "[" in return_type and "]" in return_type:
                                # Extract both PaginatedResponse and User from PaginatedResponse[User]
                                base_type = return_type.split("[")[0]
                                inner_type = return_type.split("[")[1].split("]")[0]

                                # Only add to imports if they look like model names (start with capital)
                                if base_type[0].isupper():
                                    self.model_imports.add(base_type)
                                if inner_type[0].isupper():
                                    self.model_imports.add(inner_type)
                            else:
                                # Simple type like User or ErrorResponse
                                if return_type[0].isupper():
                                    self.model_imports.add(return_type)
                        break

        # Determine status code for decorator
        # Use response status code if specified, otherwise use defaults based on method
        status_code = response_status_code
        if status_code is None:
            if method_lower == "post":
                status_code = 201  # Created
            elif method_lower == "delete":
                status_code = 204  # No Content

        # Build decorator
        decorator_params = [f"'{path}'"]

        # WebSocket endpoints have different decorator parameters than HTTP endpoints
        if method_lower == "ws":
            # WebSocket only supports: path, name, dependencies
            # Use 'name' parameter instead of 'operation_id'
            decorator_params.append(f'name="{function_name}"')
        else:
            # HTTP endpoints support all the standard parameters
            if status_code:
                decorator_params.append(f"status_code={status_code}")

            # Add operation_id
            decorator_params.append(f'operation_id="{function_name}"')

            # Add summary if provided
            if "summary" in endpoint_def:
                summary = endpoint_def["summary"].replace('"', '\\"')
                decorator_params.append(f'summary="{summary}"')

            # Add tags if provided
            if "tags" in endpoint_def:
                tags = endpoint_def["tags"]
                if isinstance(tags, list):
                    # Format tags as a Python list with proper quoting
                    tags_str = "[" + ", ".join(f'"{tag}"' for tag in tags) + "]"
                    decorator_params.append(f"tags={tags_str}")

        # Check for rate limiting
        rate_limit_decorator = ""
        if "rate_limit" in endpoint_def:
            rate_limit = endpoint_def["rate_limit"]
            # Mark that we need rate limiting support
            self.has_rate_limiting = True
            # Add rate limit decorator before the route decorator
            rate_limit_decorator = f"@limiter.limit(\"{rate_limit}\")\n"
            self.imports.add("from fastapi import Request")

        # Map 'ws' to 'websocket' for FastAPI's APIRouter decorator
        router_method = "websocket" if method_lower == "ws" else method_lower
        decorator = f"@router.{router_method}({', '.join(decorator_params)})"

        # Add rate_limit parameter to function if rate limiting is enabled
        if "rate_limit" in endpoint_def:
            # Add request parameter for rate limiting (required parameter, no default)
            required_params.append("request: Request")

        # Recombine params after potentially adding request parameter
        params = required_params + optional_params

        # Build function signature
        params_str = ", ".join(params) if params else ""
        function_signature = f"async def {function_name}({params_str}) -> {return_type}:"

        # Add description as docstring
        description = endpoint_def.get("description", "")
        docstring = f'    """{description}"""' if description else ""

        # Generate function body
        function_body_lines = []

        # Add response header setting code if headers are defined
        if has_response_headers:
            header_code = self._generate_response_header_code(endpoint_def)
            if header_code:
                function_body_lines.append(header_code)

        # Add background task comment if needed
        has_background_task = endpoint_def.get("background_task") is True
        if has_background_task:
            function_body_lines.append("    # TODO: Implement")
            function_body_lines.append("    # Example: background_tasks.add_task(some_background_function, arg1, arg2)")
        else:
            function_body_lines.append("    # TODO: Implement")

        function_body_lines.append("    pass")
        function_body = "\n".join(function_body_lines)

        # Combine all parts
        lines = []
        if rate_limit_decorator:
            lines.append(rate_limit_decorator.rstrip())
        lines.append(decorator)
        lines.append(function_signature)
        if docstring:
            lines.append(docstring)
        lines.append(function_body)

        return "\n".join(lines)

    def _get_python_type(self, schema_type: str) -> str:
        """
        Map schema type to Python type.

        Args:
            schema_type: Type from schema (e.g., "string", "int", "uuid")

        Returns:
            Python type string (e.g., "str", "int", "UUID")
        """
        schema_type_lower = schema_type.lower()

        # Handle list types: list<string> -> list[str]
        if schema_type_lower.startswith("list<") and schema_type_lower.endswith(">"):
            inner_type = schema_type_lower[5:-1].strip()
            inner_python_type = PYTHON_TYPE_MAP.get(inner_type, inner_type)
            return f"list[{inner_python_type}]"

        # Handle standard types
        return PYTHON_TYPE_MAP.get(schema_type_lower, schema_type)

    def _format_default(self, value: Any) -> str:
        """Format a default value with proper quoting for Python code.

        Args:
            value: The default value to format

        Returns:
            Formatted string representation
        """
        if value is None:
            return "None"
        elif isinstance(value, bool):
            return str(value)
        elif isinstance(value, (int, float)):
            return str(value)
        elif isinstance(value, str):
            # Use double quotes and escape quotes/backslashes
            escaped = value.replace("\\", "\\\\").replace('"', '\\"')
            return f'"{escaped}"'
        else:
            # For complex types, use repr
            return repr(value)

    def _collect_imports(self) -> None:
        """Collect necessary imports for generated routes."""
        # Collect FastAPI imports and merge them into a single line
        fastapi_imports = {"APIRouter"}

        # Check if Depends was added during generation
        if any("from fastapi import Depends" in imp for imp in self.imports):
            fastapi_imports.add("Depends")
            # Remove the separate Depends import
            self.imports.discard("from fastapi import Depends")

        # Check if Query was added during generation
        if any("from fastapi import Query" in imp for imp in self.imports):
            fastapi_imports.add("Query")
            # Remove the separate Query import
            self.imports.discard("from fastapi import Query")

        # Check if File was added during generation
        if any("from fastapi import File" in imp for imp in self.imports):
            fastapi_imports.add("File")
            # Remove the separate File import
            self.imports.discard("from fastapi import File")

        # Check if UploadFile was added during generation
        if any("from fastapi import UploadFile" in imp for imp in self.imports):
            fastapi_imports.add("UploadFile")
            # Remove the separate UploadFile import
            self.imports.discard("from fastapi import UploadFile")

        # Check if BackgroundTasks was added during generation
        if any("from fastapi import BackgroundTasks" in imp for imp in self.imports):
            fastapi_imports.add("BackgroundTasks")
            # Remove the separate BackgroundTasks import
            self.imports.discard("from fastapi import BackgroundTasks")

        # Check if Response was added during generation
        if any("from fastapi import Response" in imp for imp in self.imports):
            fastapi_imports.add("Response")
            # Remove the separate Response import
            self.imports.discard("from fastapi import Response")

        # Check if WebSocket was added during generation
        if any("from fastapi import WebSocket" in imp for imp in self.imports):
            fastapi_imports.add("WebSocket")
            # Remove the separate WebSocket import
            self.imports.discard("from fastapi import WebSocket")

        # Add merged FastAPI import
        self.imports.add(f"from fastapi import {', '.join(sorted(fastapi_imports))}")

        # Add other imports based on what was generated
        # These would be determined during generation
        # For now, we'll add common imports
        self.imports.add("from uuid import UUID")

    def _has_response_headers(self, endpoint_def: Dict[str, Any]) -> bool:
        """Check if endpoint defines response headers.

        Args:
            endpoint_def: Endpoint definition from schema

        Returns:
            True if response headers are defined
        """
        if "response" not in endpoint_def:
            return False

        responses = endpoint_def["response"]
        # Handle simple string response format (e.g., "User" or "User[]")
        if isinstance(responses, str):
            return False

        # Handle dict response format with status codes
        if isinstance(responses, dict):
            for status_code in [200, 201, 202, 204]:
                if status_code in responses:
                    response_def = responses[status_code]
                    if isinstance(response_def, dict) and "headers" in response_def:
                        return True
        return False

    def _generate_response_header_code(self, endpoint_def: Dict[str, Any]) -> str:
        """Generate code to set response headers.

        Args:
            endpoint_def: Endpoint definition from schema

        Returns:
            Python code that sets response headers
        """
        if "response" not in endpoint_def:
            return ""

        responses = endpoint_def["response"]
        # Handle simple string response format - no headers
        if isinstance(responses, str):
            return ""

        header_lines = []

        # Look for headers in successful response codes
        if not isinstance(responses, dict):
            return ""

        for status_code in [200, 201, 202, 204]:
            if status_code in responses:
                response_def = responses[status_code]
                if isinstance(response_def, dict) and "headers" in response_def:
                    headers = response_def["headers"]

                    for header_name, header_def in headers.items():
                        if isinstance(header_def, dict):
                            # Check if it's a dynamic header (computed at runtime)
                            if header_def.get("dynamic"):
                                # For dynamic headers, add a comment indicating they need to be computed
                                comment = f"    # Set dynamic header: {header_name}"
                                if "description" in header_def:
                                    comment += f" - {header_def['description']}"
                                header_lines.append(comment)
                                # Add placeholder that needs to be replaced with actual computation
                                value_placeholder = header_def.get("placeholder", "computed_value")
                                header_lines.append(f'    response.headers["{header_name}"] = str({value_placeholder})')
                            else:
                                # Static header with fixed value
                                value = header_def.get("value", "")
                                header_lines.append(f'    response.headers["{header_name}"] = "{value}"')
                        elif isinstance(header_def, str):
                            # Simple string value (static header)
                            header_lines.append(f'    response.headers["{header_name}"] = "{header_def}"')

                    break  # Only process the first matching status code

        return "\n".join(header_lines) if header_lines else ""

    def _generate_rate_limit_helper(self) -> str:
        """Generate rate limiting configuration and helper code.

        Returns:
            Python code that sets up the rate limiter
        """
        # Add slowapi import for rate limiting
        self.imports.add("from slowapi import Limiter")
        self.imports.add("from slowapi.util import get_remote_address")

        # Generate limiter configuration
        limiter_code = """
# Rate limiter configuration
limiter = Limiter(key_func=get_remote_address)
"""
        return limiter_code


# Backward-compatible alias
PythonRouteGenerator = FastAPIRouteGenerator
