"""Python settings.py generator for Schnitzel schemas.

Generates a pydantic-settings based configuration module for
FastAPI backends with typed environment variable handling.
"""

from datetime import datetime
from pathlib import Path
from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema


class SettingsGenerator:
    """Generates settings.py using pydantic-settings."""

    def generate(self, schema: SchnitzelSchema, project_name: str = "schnitzel") -> str:
        """
        Generate settings.py content with pydantic-settings.

        Args:
            schema: The Schnitzel schema
            project_name: Name of the project for default database name

        Returns:
            Generated Python code as a string
        """
        # Sanitize project name for database
        db_name = project_name.lower().replace("-", "_").replace(" ", "_")

        code = f'''"""Application settings using pydantic-settings.

Generated by Schnitzel Framework v{__version__}
Generated at: {datetime.now().isoformat()}

Configuration is loaded from environment variables with fallback defaults.
Create a .env file in the backend directory to override settings.
"""

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application configuration with environment variable support."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
    )

    # Database configuration
    database_url: str = "postgresql+asyncpg://schnitzel:schnitzel@localhost:5432/{db_name}"

    # Application settings
    debug: bool = False
    app_name: str = "{project_name}"
    api_prefix: str = "/api"

    # CORS settings
    cors_origins: list[str] = ["*"]
    cors_allow_credentials: bool = True

    # Server settings
    host: str = "0.0.0.0"
    port: int = 8000


# Global settings instance
settings = Settings()
'''
        return code

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        project_name: str = "schnitzel",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate settings.py and write it to a file.

        Args:
            schema: The Schnitzel schema
            output_dir: Directory where settings.py should be written
            project_name: Name of the project
            dry_run: If True, return file info without writing

        Returns:
            Tuple of (Path to settings.py, size in bytes)
        """
        output_path = Path(output_dir)

        if not dry_run:
            output_path.mkdir(parents=True, exist_ok=True)

        code = self.generate(schema, project_name=project_name)
        output_file = output_path / "settings.py"

        if not dry_run:
            output_file.write_text(code, encoding='utf-8')

        size = len(code.encode('utf-8'))
        return output_file, size

    def generate_env_template(self, schema: SchnitzelSchema, project_name: str = "schnitzel") -> str:
        """
        Generate .env.example template file.

        Args:
            schema: The Schnitzel schema
            project_name: Name of the project

        Returns:
            Generated .env.example content
        """
        db_name = project_name.lower().replace("-", "_").replace(" ", "_")

        return f'''# Environment configuration for {project_name}
# Copy this file to .env and adjust values as needed

# Database connection (async PostgreSQL)
DATABASE_URL=postgresql+asyncpg://schnitzel:schnitzel@localhost:5432/{db_name}

# Application settings
DEBUG=false
APP_NAME={project_name}
API_PREFIX=/api

# CORS settings (comma-separated origins for production)
CORS_ORIGINS=["*"]
CORS_ALLOW_CREDENTIALS=true

# Server settings
HOST=0.0.0.0
PORT=8000
'''
