"""Python pytest fixtures generator for Schnitzel schemas.

Generates pytest fixtures for testing, including repository mocks and sample data.
"""

from datetime import datetime
from pathlib import Path
from typing import Set
from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema, Model, FieldDefinition


class PythonTestFixturesGenerator:
    """Generates pytest fixtures for testing from Schnitzel schemas."""

    def __init__(self):
        """Initialize the test fixtures generator."""
        self.imports: Set[str] = set()
        self.model_imports: Set[str] = set()

    def generate(self, schema: SchnitzelSchema) -> str:
        """
        Generate pytest fixtures from a schema.

        Args:
            schema: The Schnitzel schema to generate fixtures from

        Returns:
            Generated Python conftest.py code as a string
        """
        self.imports = set()
        self.model_imports = set()

        # Check if we have models to generate fixtures for
        if not schema.models:
            return self._generate_empty_conftest()

        # Generate fixture sections
        fixture_sections = []

        # Generate repository mock fixtures for each model
        for model_name, model in schema.models.items():
            # Add repository mock fixture
            repo_fixture = self._generate_repository_mock_fixture(model_name, model)
            fixture_sections.append(repo_fixture)

            # Add sample instance fixture
            sample_fixture = self._generate_sample_instance_fixture(model_name, model)
            fixture_sections.append(sample_fixture)

            # Add sample list fixture
            sample_list_fixture = self._generate_sample_list_fixture(model_name, model)
            fixture_sections.append(sample_list_fixture)

            # Track model import
            self.model_imports.add(model_name)

        # Collect imports
        self._collect_imports()

        # Build final code
        imports_code = self._build_imports()
        fixtures_code = "\n\n".join(fixture_sections)

        return f"{imports_code}\n\n\n{fixtures_code}\n"

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate pytest fixtures and write them to conftest.py.

        Creates the output directory if it doesn't exist, adds a header comment with
        generation metadata, and writes the fixtures to 'conftest.py' in the specified directory.

        Args:
            schema: The Schnitzel schema to generate fixtures from
            output_dir: Directory where conftest.py should be written (can be string or Path)
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            Tuple of (Path object pointing to conftest.py file, size in bytes)

        Example:
            >>> generator = PythonTestFixturesGenerator()
            >>> output_path, size = generator.generate_to_file(schema, "backend/tests")
            >>> print(f"Fixtures written to: {output_path} ({size} bytes)")
        """
        # Convert to Path object
        output_path = Path(output_dir)

        # Generate the fixtures code
        fixtures_code = self.generate(schema)

        # Build header comment
        timestamp = datetime.now().isoformat()
        header = f"""# Generated by Schnitzel Framework v{__version__}
# DO NOT EDIT - This file is auto-generated
# Generated at: {timestamp}
# Source: {schema_source}

"""

        # Combine header with generated code
        full_code = header + fixtures_code

        # Calculate file path and size
        conftest_file = output_path / "conftest.py"
        file_size = len(full_code.encode("utf-8"))

        # If dry-run, return without writing
        if dry_run:
            return conftest_file, file_size

        # Create directory if it doesn't exist
        output_path.mkdir(parents=True, exist_ok=True)

        # Warn if file already exists
        if conftest_file.exists():
            print(f"Warning: Overwriting existing file: {conftest_file}")

        conftest_file.write_text(full_code, encoding="utf-8")

        return conftest_file, file_size

    def _generate_empty_conftest(self) -> str:
        """Generate minimal conftest.py when no models are defined."""
        self.imports.add("import pytest")
        imports_code = "\n".join(sorted(self.imports))
        return f"{imports_code}\n"

    def _generate_repository_mock_fixture(self, model_name: str, model: Model) -> str:
        """Generate a pytest fixture for a mocked repository.

        Args:
            model_name: Name of the model (e.g., "User")
            model: Model definition

        Returns:
            Fixture code as string
        """
        repo_name = f"{self._to_snake_case(model_name)}_repository"
        fixture_name = f"mock_{repo_name}"

        # Determine if we should use AsyncMock (default) or MagicMock
        # For modern async codebases, we use AsyncMock
        mock_type = "MagicMock"

        fixture_code = f'''@pytest.fixture
def {fixture_name}():
    """Mock {model_name}Repository for testing."""
    repo = {mock_type}()
    repo.get_all = AsyncMock(return_value=[])
    repo.get_by_id = AsyncMock(return_value=None)
    repo.create = AsyncMock(side_effect=lambda item: item)
    repo.update = AsyncMock(side_effect=lambda item: item)
    repo.delete = AsyncMock(return_value=None)
    return repo'''

        return fixture_code

    def _generate_sample_instance_fixture(self, model_name: str, model: Model) -> str:
        """Generate a pytest fixture for a sample model instance.

        Args:
            model_name: Name of the model (e.g., "User")
            model: Model definition

        Returns:
            Fixture code as string
        """
        fixture_name = f"sample_{self._to_snake_case(model_name)}"

        # Generate field values
        field_values = []
        for field_name, field_def in model.fields.items():
            value = self._generate_sample_value(field_name, field_def, index=0)
            if value is not None:
                field_values.append(f"        {field_name}={value}")

        fields_str = ",\n".join(field_values) if field_values else ""

        fixture_code = f'''@pytest.fixture
def {fixture_name}():
    """Sample {model_name} instance for testing."""
    return {model_name}(
{fields_str}
    )'''

        return fixture_code

    def _generate_sample_list_fixture(self, model_name: str, model: Model) -> str:
        """Generate a pytest fixture for a list of sample model instances.

        Args:
            model_name: Name of the model (e.g., "User")
            model: Model definition

        Returns:
            Fixture code as string
        """
        fixture_name = f"sample_{self._to_snake_case(model_name)}s"
        snake_name = self._to_snake_case(model_name)

        # Generate a list of 3 instances with different values
        instances = []
        for i in range(3):
            field_values = []
            for field_name, field_def in model.fields.items():
                value = self._generate_sample_value(field_name, field_def, index=i)
                if value is not None:
                    field_values.append(f"{field_name}={value}")

            fields_str = ", ".join(field_values) if field_values else ""
            instances.append(f"{model_name}({fields_str})")

        # Format instances list
        instances_str = ",\n        ".join(instances)

        fixture_code = f'''@pytest.fixture
def {fixture_name}():
    """List of sample {model_name} instances."""
    return [
        {instances_str}
    ]'''

        return fixture_code

    def _generate_sample_value(self, field_name: str, field_def: FieldDefinition, index: int = 0) -> str | None:
        """Generate a sample value for a field based on its type.

        Args:
            field_name: Name of the field
            field_def: Field definition
            index: Index for generating varied values (for lists)

        Returns:
            Python code string representing the sample value, or None if field is optional without default
        """
        field_type_lower = field_def.type.lower()

        # Handle primary key fields specially
        if field_def.primary:
            if field_type_lower == "uuid":
                return f'"test-uuid-{index}"'
            elif field_type_lower in ["int", "integer"]:
                return str(index + 1)
            elif field_type_lower in ["string", "str"]:
                return f'"id-{index}"'

        # Handle common field types
        if field_type_lower == "uuid":
            return f'"uuid-{index}"'
        elif field_type_lower in ["string", "str", "text"]:
            # Generate sensible defaults based on field name
            if "email" in field_name.lower():
                return f'"user{index}@example.com"'
            elif "name" in field_name.lower():
                return f'"{field_name.title()} {index}"'
            elif "url" in field_name.lower():
                return f'"https://example.com/{index}"'
            else:
                return f'"test-{field_name}-{index}"'
        elif field_type_lower in ["int", "integer"]:
            default = field_def.default if field_def.default is not None else 0
            return str(default + index)
        elif field_type_lower == "float":
            default = field_def.default if field_def.default is not None else 0.0
            return str(default + index * 0.1)
        elif field_type_lower in ["bool", "boolean"]:
            return str(field_def.default if field_def.default is not None else (index % 2 == 0))
        elif field_type_lower == "datetime":
            return '"2024-01-01T00:00:00"'
        elif field_type_lower == "date":
            return '"2024-01-01"'
        elif field_type_lower == "json":
            return f'{{"key": "value{index}"}}'
        elif field_type_lower == "enum" and field_def.values:
            # Use first enum value
            return f'"{field_def.values[0]}"'
        elif field_type_lower.startswith("list<"):
            # Return empty list for simplicity
            return "[]"

        # For optional fields without default, return None
        if field_def.optional and field_def.default is None:
            return "None"

        # For other types, return a generic string
        return f'"test-{field_name}"'

    def _collect_imports(self) -> None:
        """Collect necessary imports for generated fixtures."""
        # Base pytest import
        self.imports.add("import pytest")

        # Mock imports
        self.imports.add("from unittest.mock import MagicMock, AsyncMock")

        # Model imports will be added in _build_imports()

    def _build_imports(self) -> str:
        """Build the imports section of the generated code.

        Returns:
            Formatted imports string
        """
        # Sort standard imports
        imports_list = sorted(self.imports)
        imports_code = "\n".join(imports_list)

        # Add model imports if any
        if self.model_imports:
            model_imports_str = ", ".join(sorted(self.model_imports))
            imports_code += f"\nfrom app.models import {model_imports_str}"

        return imports_code

    def _to_snake_case(self, name: str) -> str:
        """Convert PascalCase or camelCase to snake_case.

        Args:
            name: Name in PascalCase or camelCase

        Returns:
            Name in snake_case
        """
        import re
        # Insert underscore before uppercase letters and convert to lowercase
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
        return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()
