"""Python factory_boy test factory generator for Schnitzel schemas.

Generates factory_boy Factory classes for testing SQLAlchemy models.
"""

from datetime import datetime
from pathlib import Path
from typing import Set
from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema, Model, FieldDefinition, Relation


class PythonTestFactoryGenerator:
    """Generates factory_boy test factories from Schnitzel schemas."""

    def __init__(self):
        """Initialize the Python test factory generator."""
        self.imports: Set[str] = set()

    def generate(self, schema: SchnitzelSchema) -> str:
        """
        Generate factory_boy test factories from a schema.

        Args:
            schema: The Schnitzel schema to generate factories from

        Returns:
            Generated Python code as a string
        """
        self.imports = set()

        # Generate factory classes
        factory_code_sections = []
        for model_name, model in schema.models.items():
            factory_code = self._generate_factory(model)
            factory_code_sections.append(factory_code)

        # Collect imports based on field types
        self._collect_imports(schema)

        # Add base imports
        self.imports.add("import factory")
        self.imports.add("from uuid import uuid4")
        self.imports.add("from datetime import datetime")

        # Build import statement for models
        model_names = ", ".join(schema.models.keys())
        self.imports.add(f"from app.models import {model_names}")

        # Build final code
        imports_code = "\n".join(sorted(self.imports))
        factories_code = "\n\n\n".join(factory_code_sections)

        return f"{imports_code}\n\n\n{factories_code}\n"

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate factory_boy test factories and write them to a file.

        Creates the output directory if it doesn't exist, adds a header comment with
        generation metadata, and writes the factories to 'factories.py' in the specified directory.

        Args:
            schema: The Schnitzel schema to generate factories from
            output_dir: Directory where factories.py should be written (can be string or Path)
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            Tuple of (Path object pointing to factories.py file, size in bytes)

        Example:
            >>> generator = PythonTestFactoryGenerator()
            >>> output_path, size = generator.generate_to_file(schema, "backend/app/tests")
            >>> print(f"Factories written to: {output_path} ({size} bytes)")
        """
        # Convert to Path object
        output_path = Path(output_dir)

        # Generate the factory code
        factories_code = self.generate(schema)

        # Build header comment
        timestamp = datetime.now().isoformat()
        header = f"""# Generated by Schnitzel Framework v{__version__}
# DO NOT EDIT - This file is auto-generated
# Generated at: {timestamp}
# Source: {schema_source}

"""

        # Combine header with generated code
        full_code = header + factories_code

        # Calculate file path and size
        factories_file = output_path / "factories.py"
        file_size = len(full_code.encode("utf-8"))

        # If dry-run, return without writing
        if dry_run:
            return factories_file, file_size

        # Create directory if it doesn't exist
        output_path.mkdir(parents=True, exist_ok=True)

        # Warn if file already exists
        if factories_file.exists():
            print(f"Warning: Overwriting existing file: {factories_file}")

        factories_file.write_text(full_code, encoding="utf-8")

        return factories_file, file_size

    def _generate_factory(self, model: Model) -> str:
        """Generate a single factory_boy Factory class."""
        lines = [f"class {model.name}Factory(factory.Factory):"]

        # Add Meta class
        lines.append("    class Meta:")
        lines.append(f"        model = {model.name}")
        lines.append("")

        # Generate field definitions
        if model.fields:
            for field_name, field_def in model.fields.items():
                # Skip primary key auto fields
                if field_def.primary and field_def.auto:
                    continue

                field_line = self._generate_factory_field(field_name, field_def)
                lines.append(f"    {field_line}")

        # Generate relationship fields
        if model.relations:
            lines.append("")
            for relation_name, relation_def in model.relations.items():
                relation_line = self._generate_relationship_field(relation_name, relation_def)
                if relation_line:
                    lines.append(f"    {relation_line}")

        return "\n".join(lines)

    def _generate_factory_field(self, field_name: str, field_def: FieldDefinition) -> str:
        """Generate a single factory field definition.

        Maps field types to appropriate factory_boy generators:
        - uuid: factory.LazyFunction(lambda: str(uuid4()))
        - string (email): factory.Sequence(lambda n: f'user{n}@example.com')
        - string (name): factory.Faker('name')
        - string (other): factory.Faker('word')
        - int: factory.Faker('random_int', min=0, max=1000)
        - float: factory.Faker('pyfloat', min_value=0, max_value=100)
        - bool: factory.Faker('boolean')
        - datetime: factory.LazyFunction(datetime.utcnow)
        - text: factory.Faker('paragraph')
        """
        field_type_lower = field_def.type.lower()

        # Handle UUID fields
        if field_type_lower == "uuid" or field_name == "id":
            return f"{field_name} = factory.LazyFunction(lambda: str(uuid4()))"

        # Handle datetime fields
        if field_type_lower in ("datetime", "date"):
            return f"{field_name} = factory.LazyFunction(datetime.utcnow)"

        # Handle string fields with special cases
        if field_type_lower in ("string", "str"):
            # Email fields
            if "email" in field_name.lower():
                return f"{field_name} = factory.Sequence(lambda n: f'user{{n}}@example.com')"
            # Name fields
            elif "name" in field_name.lower():
                return f"{field_name} = factory.Faker('name')"
            # Generic string
            else:
                return f"{field_name} = factory.Faker('word')"

        # Handle text fields
        if field_type_lower == "text":
            return f"{field_name} = factory.Faker('paragraph')"

        # Handle integer fields
        if field_type_lower in ("int", "integer"):
            return f"{field_name} = factory.Faker('random_int', min=0, max=1000)"

        # Handle float/double fields
        if field_type_lower in ("float", "double"):
            return f"{field_name} = factory.Faker('pyfloat', min_value=0, max_value=100)"

        # Handle boolean fields
        if field_type_lower in ("bool", "boolean"):
            return f"{field_name} = factory.Faker('boolean')"

        # Default fallback
        return f"{field_name} = factory.Faker('word')"

    def _generate_relationship_field(self, relation_name: str, relation_def: Relation) -> str:
        """Generate a relationship field definition using SubFactory.

        Args:
            relation_name: Name of the relationship field
            relation_def: Relation definition from schema

        Returns:
            Field definition string or empty string if not supported

        Supported relationships:
            - belongsTo: generates factory.SubFactory(RelatedModelFactory)
        """
        # Handle belongsTo relationship
        if relation_def.type == "belongsTo":
            return f"{relation_name} = factory.SubFactory({relation_def.model}Factory)"

        # hasMany, hasOne not typically used in factories
        return ""

    def _collect_imports(self, schema: SchnitzelSchema) -> None:
        """Collect necessary imports based on field types used."""
        # All imports are handled in generate() method
        # This method is kept for consistency with other generators
        pass
