"""Python FastAPI WebSocket handler generator for Schnitzel schemas.

Generates FastAPI WebSocket endpoints with connection management, message routing,
heartbeat mechanism, and authentication support.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List
from jinja2 import Environment, PackageLoader, select_autoescape
import re

from schnitzel.schema.models import SchnitzelSchema, PYTHON_TYPE_MAP
from schnitzel.generators.validation_utils import validate_message_type_uniqueness


class WebSocketHandlerGenerator:
    """Generates FastAPI WebSocket handlers from Schnitzel schemas."""

    def __init__(self):
        """Initialize the WebSocket handler generator."""
        self.env = Environment(
            loader=PackageLoader('schnitzel', 'templates/python'),
            autoescape=select_autoescape(),
        )

    def generate(self, schema: SchnitzelSchema) -> str:
        """
        Generate Python FastAPI WebSocket handlers from a schema.

        Args:
            schema: The Schnitzel schema to generate WebSocket handlers from

        Returns:
            Generated Python code as a string
        """
        # Check if schema has streams section
        if not schema.streams:
            return self._generate_empty_websocket()

        # Filter streams by type='websocket'
        websocket_streams = []
        needs_uuid = False
        needs_auth = False

        for name, stream_def in schema.streams.items():
            # Handle both StreamConfig objects and plain dicts
            stream_type = self._get_attr(stream_def, "type")
            if stream_type == "websocket":
                stream_info = self._parse_stream(name, stream_def)
                websocket_streams.append(stream_info)

                # Check if UUID is needed
                for param in stream_info['path_params']:
                    if param['python_type'] == 'UUID':
                        needs_uuid = True

                # Check if auth is needed
                auth = stream_info.get('auth')
                if auth in ['required', 'optional']:
                    needs_auth = True

        if not websocket_streams:
            return self._generate_empty_websocket()

        # Load and render template
        template = self.env.get_template("websocket.py.j2")
        rendered = template.render(
            streams=websocket_streams,
            needs_uuid=needs_uuid,
            needs_auth=needs_auth
        )
        return rendered

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate Python FastAPI WebSocket handlers and write them to a file.

        Creates the output directory if it doesn't exist, adds a header comment with
        generation metadata, and writes the handlers to 'websocket.py' in the specified directory.

        Args:
            schema: The Schnitzel schema to generate WebSocket handlers from
            output_dir: Directory where websocket.py should be written (can be string or Path)
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            Tuple of (Path object pointing to websocket.py file, size in bytes)

        Example:
            >>> generator = WebSocketHandlerGenerator()
            >>> output_path, size = generator.generate_to_file(schema, "backend/app/generated")
            >>> print(f"WebSocket handlers written to: {output_path} ({size} bytes)")
        """
        # Convert to Path object
        output_path = Path(output_dir)

        # Generate the WebSocket code
        websocket_code = self.generate(schema)

        # Build header comment
        timestamp = datetime.now().isoformat()
        header = f"""# Generated by Schnitzel Framework
# DO NOT EDIT - This file is auto-generated
# Generated at: {timestamp}
# Source: {schema_source}

"""

        # Combine header with generated code
        full_code = header + websocket_code

        # Calculate file path and size
        websocket_file = output_path / "websocket.py"
        file_size = len(full_code.encode("utf-8"))

        # If dry-run, return without writing
        if dry_run:
            return websocket_file, file_size

        # Create directory if it doesn't exist
        output_path.mkdir(parents=True, exist_ok=True)

        # Warn if file already exists
        if websocket_file.exists():
            print(f"Warning: Overwriting existing file: {websocket_file}")

        websocket_file.write_text(full_code, encoding="utf-8")

        return websocket_file, file_size

    def _generate_empty_websocket(self) -> str:
        """Generate a minimal websocket file when no WebSocket streams are defined."""
        return '''"""WebSocket handlers (no streams defined)."""

from fastapi import APIRouter


router = APIRouter()
'''

    def _get_attr(self, obj: Any, attr: str, default: Any = None) -> Any:
        """Get attribute from StreamConfig object or dict.

        Args:
            obj: StreamConfig object or dict
            attr: Attribute name
            default: Default value if attribute not found

        Returns:
            Attribute value or default
        """
        if hasattr(obj, attr):
            return getattr(obj, attr, default)
        elif isinstance(obj, dict):
            return obj.get(attr, default)
        return default

    def _parse_stream(self, stream_name: str, stream_def: Any) -> Dict[str, Any]:
        """Parse a stream definition into template data.

        Args:
            stream_name: Name of the stream
            stream_def: Stream definition from schema (StreamConfig or dict)

        Returns:
            Dictionary with stream information for template

        Raises:
            ValueError: If validation fails
        """
        path = self._get_attr(stream_def, "path", f"/ws/{stream_name}")
        description = self._get_attr(stream_def, "description")
        auth = self._get_attr(stream_def, "auth", "required")
        messages = self._get_attr(stream_def, "messages", [])

        # Validate message type uniqueness (F102)
        if messages:
            try:
                validate_message_type_uniqueness(messages)
            except ValueError as e:
                raise ValueError(f"Stream '{stream_name}': {e}") from e

        # Extract path parameters
        path_params = []
        param_names = re.findall(r'\{(\w+)\}', path)
        for param_name in param_names:
            # Default to UUID for id-like params, str otherwise
            if param_name.endswith('_id') or param_name == 'id':
                python_type = 'UUID'
            else:
                python_type = 'str'

            path_params.append({
                'name': param_name,
                'python_type': python_type
            })

        # Parse messages
        parsed_messages = []
        for msg in messages:
            if hasattr(msg, 'type'):
                # MessageConfig object
                msg_type = msg.type
                msg_payload = msg.payload
                msg_description = getattr(msg, 'description', None)
            elif isinstance(msg, dict):
                # Dict
                msg_type = msg.get('type', '')
                msg_payload = msg.get('payload', {})
                msg_description = msg.get('description')
            else:
                continue

            # Parse payload fields
            payload_fields = {}
            for field_name, field_type in (msg_payload.items() if isinstance(msg_payload, dict) else []):
                python_type = self._get_python_type(field_type)
                payload_fields[field_name] = {
                    'python_type': python_type,
                    'optional': False
                }

            # Generate payload class name
            payload_class_name = f"{self._to_pascal_case(stream_name)}{self._to_pascal_case(msg_type)}Payload"

            parsed_messages.append({
                'type': msg_type,
                'description': msg_description,
                'payload_fields': payload_fields,
                'payload_class_name': payload_class_name
            })

        # Generate function name
        function_name = self._to_snake_case(stream_name)

        return {
            'name': stream_name,
            'function_name': function_name,
            'path': path,
            'description': description,
            'auth': auth,
            'path_params': path_params,
            'messages': parsed_messages
        }

    def _to_pascal_case(self, name: str) -> str:
        """Convert a name to PascalCase.

        Args:
            name: Name to convert (e.g., "order_updates" or "order.placed")

        Returns:
            PascalCase name (e.g., "OrderUpdates" or "OrderPlaced")
        """
        # Replace dots and underscores with spaces, then title case
        words = re.sub(r'[._-]', ' ', name).split()
        return ''.join(word.capitalize() for word in words)

    def _to_snake_case(self, name: str) -> str:
        """Convert a name to snake_case.

        Args:
            name: Name to convert

        Returns:
            snake_case name
        """
        # Replace dots and dashes with underscores
        name = re.sub(r'[.-]', '_', name)
        # Insert underscore before uppercase letters
        name = re.sub(r'([a-z])([A-Z])', r'\1_\2', name)
        return name.lower()

    def _get_python_type(self, schema_type: str) -> str:
        """Map schema type to Python type.

        Args:
            schema_type: Type from schema

        Returns:
            Python type string
        """
        if isinstance(schema_type, dict):
            # Handle complex types
            return 'Any'

        schema_type_lower = schema_type.lower()

        # Handle list types
        if schema_type_lower.startswith("list<") and schema_type_lower.endswith(">"):
            inner_type = schema_type_lower[5:-1].strip()
            inner_python_type = PYTHON_TYPE_MAP.get(inner_type, inner_type)
            return f"list[{inner_python_type}]"

        # Handle enum types
        if schema_type_lower == "enum":
            return "str"

        # Handle standard types
        return PYTHON_TYPE_MAP.get(schema_type_lower, schema_type)
