"""Integration tests for F052 - Generate command with --target all generates Python, Dart, and Docker files.

Test Requirements:
- test_generate_all_creates_python_models
- test_generate_all_creates_dart_models
- test_generate_all_target_is_default
- test_generate_output_directory_structure
"""

import tempfile
import os
from pathlib import Path
from typer.testing import CliRunner
import pytest

from schnitzel.cli import app

runner = CliRunner()


@pytest.fixture
def temp_dir():
    """Create a temporary directory for testing and change to it."""
    original_cwd = os.getcwd()
    with tempfile.TemporaryDirectory() as tmpdir:
        os.chdir(tmpdir)
        yield Path(tmpdir)
        os.chdir(original_cwd)


@pytest.fixture
def schema_file(temp_dir: Path) -> Path:
    """Create a test schema file."""
    schema_content = """schnitzel: 1.0.0

models:
  User:
    description: A user in the system
    fields:
      id:
        type: uuid
        primary: true
      name:
        type: string
      email:
        type: string
        unique: true
      created_at:
        type: datetime
        auto: create

  Post:
    description: A blog post
    fields:
      id:
        type: uuid
        primary: true
      title:
        type: string
      content:
        type: string
      author_id:
        type: uuid
      created_at:
        type: datetime
        auto: create
    relations:
      author:
        type: belongsTo
        model: User
        foreign_key: author_id
"""
    schema_file = temp_dir / "schema.schnitzel.yaml"
    schema_file.write_text(schema_content)
    return schema_file


def test_generate_all_creates_python_models(temp_dir: Path, schema_file: Path) -> None:
    """Test that generate --target all creates Python Pydantic models."""
    # Run generate command with --target all
    result = runner.invoke(app, ["generate", str(schema_file), "--target", "all", "--output", str(temp_dir)])

    # Verify command succeeded
    assert result.exit_code == 0, f"Command failed: {result.stdout}"

    # Verify Python models were created
    python_models_file = temp_dir / "backend" / "app" / "models.py"
    assert python_models_file.exists(), "Python models.py not created"
    assert python_models_file.is_file(), "Python models.py is not a file"

    # Verify content
    content = python_models_file.read_text()
    assert "class User(BaseModel):" in content, "Missing User model"
    assert "class Post(BaseModel):" in content, "Missing Post model"
    assert "from pydantic import BaseModel" in content, "Missing pydantic import"
    assert "Generated by Schnitzel Framework" in content, "Missing header comment"


def test_generate_all_creates_dart_models(temp_dir: Path, schema_file: Path) -> None:
    """Test that generate --target all creates Dart Freezed models."""
    # Run generate command with --target all
    result = runner.invoke(app, ["generate", str(schema_file), "--target", "all", "--output", str(temp_dir)])

    # Verify command succeeded
    assert result.exit_code == 0, f"Command failed: {result.stdout}"

    # Verify Dart models were created
    dart_models_file = temp_dir / "packages" / "app" / "lib" / "models" / "models.dart"
    assert dart_models_file.exists(), "Dart models.dart not created"
    assert dart_models_file.is_file(), "Dart models.dart is not a file"

    # Verify content
    content = dart_models_file.read_text()
    assert "class User with" in content, "Missing User model"
    assert "class Post with" in content, "Missing Post model"
    assert "@freezed" in content, "Missing @freezed annotation"
    assert "import 'package:freezed_annotation/freezed_annotation.dart';" in content, "Missing freezed import"
    assert "Generated by Schnitzel Framework" in content, "Missing header comment"


def test_generate_all_target_is_default(temp_dir: Path, schema_file: Path) -> None:
    """Test that --target all is the default behavior (no --target flag)."""
    # Run generate command without --target flag
    result = runner.invoke(app, ["generate", str(schema_file), "--output", str(temp_dir)])

    # Verify command succeeded
    assert result.exit_code == 0, f"Command failed: {result.stdout}"

    # Verify Python models were created
    python_models_file = temp_dir / "backend" / "app" / "models.py"
    assert python_models_file.exists(), "Python models.py not created with default target"

    # Verify Dart models were created
    dart_models_file = temp_dir / "packages" / "app" / "lib" / "models" / "models.dart"
    assert dart_models_file.exists(), "Dart models.dart not created with default target"

    # Verify Docker compose was created
    docker_compose_file = temp_dir / "docker-compose.yaml"
    assert docker_compose_file.exists(), "docker-compose.yaml not created with default target"


def test_generate_output_directory_structure(temp_dir: Path, schema_file: Path) -> None:
    """Test that generate creates the correct directory structure."""
    # Run generate command with --target all
    result = runner.invoke(app, ["generate", str(schema_file), "--target", "all", "--output", str(temp_dir)])

    # Verify command succeeded
    assert result.exit_code == 0, f"Command failed: {result.stdout}"

    # Verify backend directory structure
    backend_dir = temp_dir / "backend"
    assert backend_dir.exists(), "backend directory not created"
    assert backend_dir.is_dir(), "backend is not a directory"

    backend_app_dir = temp_dir / "backend" / "app"
    assert backend_app_dir.exists(), "backend/app directory not created"
    assert backend_app_dir.is_dir(), "backend/app is not a directory"

    # Verify Flutter/Dart directory structure
    packages_dir = temp_dir / "packages"
    assert packages_dir.exists(), "packages directory not created"
    assert packages_dir.is_dir(), "packages is not a directory"

    app_dir = temp_dir / "packages" / "app"
    assert app_dir.exists(), "packages/app directory not created"
    assert app_dir.is_dir(), "packages/app is not a directory"

    lib_dir = temp_dir / "packages" / "app" / "lib"
    assert lib_dir.exists(), "packages/app/lib directory not created"
    assert lib_dir.is_dir(), "packages/app/lib is not a directory"

    models_dir = temp_dir / "packages" / "app" / "lib" / "models"
    assert models_dir.exists(), "packages/app/lib/models directory not created"
    assert models_dir.is_dir(), "packages/app/lib/models is not a directory"


def test_generate_python_target_only(temp_dir: Path, schema_file: Path) -> None:
    """Test that --target python generates only Python models."""
    # Run generate command with --target python
    result = runner.invoke(app, ["generate", str(schema_file), "--target", "python", "--output", str(temp_dir)])

    # Verify command succeeded
    assert result.exit_code == 0, f"Command failed: {result.stdout}"

    # Verify Python models were created
    python_models_file = temp_dir / "backend" / "app" / "models.py"
    assert python_models_file.exists(), "Python models.py not created"

    # Verify Dart models were NOT created
    dart_models_file = temp_dir / "packages" / "app" / "lib" / "models" / "models.dart"
    assert not dart_models_file.exists(), "Dart models.dart should not be created with --target python"

    # Verify Docker compose was NOT created
    docker_compose_file = temp_dir / "docker-compose.yaml"
    assert not docker_compose_file.exists(), "docker-compose.yaml should not be created with --target python"


def test_generate_flutter_target_only(temp_dir: Path, schema_file: Path) -> None:
    """Test that --target flutter generates only Dart models."""
    # Run generate command with --target flutter
    result = runner.invoke(app, ["generate", str(schema_file), "--target", "flutter", "--output", str(temp_dir)])

    # Verify command succeeded
    assert result.exit_code == 0, f"Command failed: {result.stdout}"

    # Verify Dart models were created
    dart_models_file = temp_dir / "packages" / "app" / "lib" / "models" / "models.dart"
    assert dart_models_file.exists(), "Dart models.dart not created"

    # Verify Python models were NOT created
    python_models_file = temp_dir / "backend" / "app" / "models.py"
    assert not python_models_file.exists(), "Python models.py should not be created with --target flutter"

    # Verify Docker compose was NOT created
    docker_compose_file = temp_dir / "docker-compose.yaml"
    assert not docker_compose_file.exists(), "docker-compose.yaml should not be created with --target flutter"


def test_generate_docker_target_only(temp_dir: Path, schema_file: Path) -> None:
    """Test that --target docker generates only docker-compose.yaml."""
    # Run generate command with --target docker
    result = runner.invoke(app, ["generate", str(schema_file), "--target", "docker", "--output", str(temp_dir)])

    # Verify command succeeded
    assert result.exit_code == 0, f"Command failed: {result.stdout}"

    # Verify Docker compose was created
    docker_compose_file = temp_dir / "docker-compose.yaml"
    assert docker_compose_file.exists(), "docker-compose.yaml not created"

    # Verify Python models were NOT created
    python_models_file = temp_dir / "backend" / "app" / "models.py"
    assert not python_models_file.exists(), "Python models.py should not be created with --target docker"

    # Verify Dart models were NOT created
    dart_models_file = temp_dir / "packages" / "app" / "lib" / "models" / "models.dart"
    assert not dart_models_file.exists(), "Dart models.dart should not be created with --target docker"


def test_generate_target_shorthand_flag(temp_dir: Path, schema_file: Path) -> None:
    """Test that -t shorthand works for --target."""
    # Run generate command with -t flag
    result = runner.invoke(app, ["generate", str(schema_file), "-t", "python", "--output", str(temp_dir)])

    # Verify command succeeded
    assert result.exit_code == 0, f"Command failed: {result.stdout}"

    # Verify Python models were created
    python_models_file = temp_dir / "backend" / "app" / "models.py"
    assert python_models_file.exists(), "Python models.py not created with -t flag"


def test_generate_output_shorthand_flag(temp_dir: Path, schema_file: Path) -> None:
    """Test that -o shorthand works for --output."""
    # Run generate command with -o flag
    result = runner.invoke(app, ["generate", str(schema_file), "-t", "python", "-o", str(temp_dir)])

    # Verify command succeeded
    assert result.exit_code == 0, f"Command failed: {result.stdout}"

    # Verify Python models were created
    python_models_file = temp_dir / "backend" / "app" / "models.py"
    assert python_models_file.exists(), "Python models.py not created with -o flag"


def test_generate_invalid_target_fails(temp_dir: Path, schema_file: Path) -> None:
    """Test that invalid target choice fails gracefully."""
    # Run generate command with invalid target
    result = runner.invoke(app, ["generate", str(schema_file), "--target", "invalid", "--output", str(temp_dir)])

    # Verify command failed
    assert result.exit_code == 1, "Command should fail with invalid target"
    assert "Invalid target" in result.stdout or "invalid" in result.stdout.lower(), \
        "Error message should mention invalid target"


def test_generate_force_flag_overwrites_files(temp_dir: Path, schema_file: Path) -> None:
    """Test that --force flag allows overwriting existing files."""
    # Run generate command first time
    result1 = runner.invoke(app, ["generate", str(schema_file), "-t", "python", "-o", str(temp_dir)])
    assert result1.exit_code == 0, f"First command failed: {result1.stdout}"

    # Verify file was created
    python_models_file = temp_dir / "backend" / "app" / "models.py"
    assert python_models_file.exists(), "Python models.py not created"

    # Get original content
    original_content = python_models_file.read_text()

    # Run generate command again without --force (should skip)
    result2 = runner.invoke(app, ["generate", str(schema_file), "-t", "python", "-o", str(temp_dir)])
    assert result2.exit_code == 0, f"Second command failed: {result2.stdout}"

    # Content should be the same (file was not overwritten)
    content_after_no_force = python_models_file.read_text()
    assert content_after_no_force == original_content, "File should not be overwritten without --force"

    # Run generate command again with --force
    result3 = runner.invoke(app, ["generate", str(schema_file), "-t", "python", "-o", str(temp_dir), "--force"])
    assert result3.exit_code == 0, f"Third command failed: {result3.stdout}"

    # Content should be different (file was overwritten with new timestamp)
    content_after_force = python_models_file.read_text()
    # Both should have content but timestamps will be different
    assert "Generated by Schnitzel Framework" in content_after_force, "File should be regenerated"


def test_generate_python_models_have_relationships(temp_dir: Path, schema_file: Path) -> None:
    """Test that generated Python models include relationships."""
    # Run generate command
    result = runner.invoke(app, ["generate", str(schema_file), "-t", "python", "-o", str(temp_dir)])
    assert result.exit_code == 0, f"Command failed: {result.stdout}"

    # Read Python models
    python_models_file = temp_dir / "backend" / "app" / "models.py"
    content = python_models_file.read_text()

    # Verify belongsTo relationship exists
    assert "author: User | None = None" in content, "Missing belongsTo relationship in Post model"
    assert "from __future__ import annotations" in content, "Missing __future__ annotations for forward references"


def test_generate_dart_models_have_relationships(temp_dir: Path, schema_file: Path) -> None:
    """Test that generated Dart models include relationships."""
    # Run generate command
    result = runner.invoke(app, ["generate", str(schema_file), "-t", "flutter", "-o", str(temp_dir)])
    assert result.exit_code == 0, f"Command failed: {result.stdout}"

    # Read Dart models
    dart_models_file = temp_dir / "packages" / "app" / "lib" / "models" / "models.dart"
    content = dart_models_file.read_text()

    # Verify belongsTo relationship exists
    assert "User?" in content and "author" in content, "Missing belongsTo relationship in Post model"


def test_generate_all_creates_docker_compose(temp_dir: Path, schema_file: Path) -> None:
    """Test that generate --target all creates docker-compose.yaml."""
    # Run generate command with --target all
    result = runner.invoke(app, ["generate", str(schema_file), "--target", "all", "--output", str(temp_dir)])

    # Verify command succeeded
    assert result.exit_code == 0, f"Command failed: {result.stdout}"

    # Verify Docker compose was created
    docker_compose_file = temp_dir / "docker-compose.yaml"
    assert docker_compose_file.exists(), "docker-compose.yaml not created"
    assert docker_compose_file.is_file(), "docker-compose.yaml is not a file"

    # Verify basic docker-compose structure
    content = docker_compose_file.read_text()
    assert "version:" in content, "Missing version field in docker-compose.yaml"
    assert "services:" in content, "Missing services section in docker-compose.yaml"
