"""Integration tests for F100: Generated files include 'DO NOT EDIT' warning header.

Test Requirements:
- test_python_has_header - Python files have warning header
- test_dart_has_header - Dart files have warning header
- test_docker_has_header - Docker files have warning header
- test_header_mentions_auto_generated - header says auto-generated
"""

import tempfile
import os
from pathlib import Path
import pytest

from schnitzel.schema.models import SchnitzelSchema, Model, FieldDefinition
from schnitzel.generators.python import PythonModelGenerator
from schnitzel.generators.dart import DartModelGenerator
from schnitzel.generators.docker.compose import DockerComposeGenerator


@pytest.fixture
def temp_dir():
    """Create a temporary directory for testing and change to it."""
    original_cwd = os.getcwd()
    with tempfile.TemporaryDirectory() as tmpdir:
        os.chdir(tmpdir)
        yield Path(tmpdir)
        os.chdir(original_cwd)


@pytest.fixture
def sample_schema():
    """Create a simple schema for testing."""
    return SchnitzelSchema(
        models={
            "User": Model(
                name="User",
                description="A user in the system",
                fields={
                    "id": FieldDefinition(type="uuid", primary=True),
                    "name": FieldDefinition(type="string"),
                    "email": FieldDefinition(type="string"),
                }
            )
        }
    )


def test_python_has_header(temp_dir: Path, sample_schema: SchnitzelSchema) -> None:
    """Test that Python generated files have a DO NOT EDIT warning header."""
    # Generate Python models
    generator = PythonModelGenerator()
    output_file, _ = generator.generate_to_file(
        sample_schema,
        temp_dir / "python",
        schema_source="test_schema.yaml"
    )

    # Read the generated file
    content = output_file.read_text(encoding="utf-8")

    # Verify header exists at the top of the file
    lines = content.split("\n")

    # First line should be a comment with "Generated by Schnitzel"
    assert lines[0].startswith("#"), "First line should be a comment"
    assert "Generated by Schnitzel" in lines[0], "Header should mention Schnitzel Framework"

    # Should have DO NOT EDIT warning
    header_text = "\n".join(lines[:10])  # Check first 10 lines
    assert "DO NOT EDIT" in header_text, "Header should contain 'DO NOT EDIT' warning"


def test_dart_has_header(temp_dir: Path, sample_schema: SchnitzelSchema) -> None:
    """Test that Dart generated files have a DO NOT EDIT warning header."""
    # Generate Dart models
    generator = DartModelGenerator()
    output_file, _ = generator.generate_to_file(
        sample_schema,
        temp_dir / "dart",
        schema_source="test_schema.yaml"
    )

    # Read the generated file
    content = output_file.read_text(encoding="utf-8")

    # Verify header exists at the top of the file
    lines = content.split("\n")

    # First line should be a comment with "Generated by Schnitzel"
    assert lines[0].startswith("//"), "First line should be a Dart comment"
    assert "Generated by Schnitzel" in lines[0], "Header should mention Schnitzel Framework"

    # Should have DO NOT EDIT warning
    header_text = "\n".join(lines[:10])  # Check first 10 lines
    assert "DO NOT EDIT" in header_text, "Header should contain 'DO NOT EDIT' warning"


def test_docker_has_header(temp_dir: Path) -> None:
    """Test that Docker Compose files have a DO NOT EDIT warning header."""
    # Generate docker-compose.yaml
    generator = DockerComposeGenerator()
    output_file, _ = generator.generate_to_file(temp_dir / "docker")

    # Read the generated file
    content = output_file.read_text(encoding="utf-8")

    # Verify header exists at the top of the file
    lines = content.split("\n")

    # First line should be a comment with "Generated by Schnitzel"
    assert lines[0].startswith("#"), "First line should be a YAML comment"
    assert "Generated by Schnitzel" in lines[0], "Header should mention Schnitzel Framework"

    # Should have DO NOT EDIT warning
    header_text = "\n".join(lines[:10])  # Check first 10 lines
    assert "DO NOT EDIT" in header_text, "Header should contain 'DO NOT EDIT' warning"


def test_header_mentions_auto_generated(temp_dir: Path, sample_schema: SchnitzelSchema) -> None:
    """Test that all generator headers mention that files are auto-generated."""
    # Test Python generator
    python_generator = PythonModelGenerator()
    python_file, _ = python_generator.generate_to_file(
        sample_schema,
        temp_dir / "python",
        schema_source="test_schema.yaml"
    )
    python_content = python_file.read_text(encoding="utf-8")
    python_header = "\n".join(python_content.split("\n")[:10])
    assert "auto-generated" in python_header, "Python header should mention 'auto-generated'"

    # Test Dart generator
    dart_generator = DartModelGenerator()
    dart_file, _ = dart_generator.generate_to_file(
        sample_schema,
        temp_dir / "dart",
        schema_source="test_schema.yaml"
    )
    dart_content = dart_file.read_text(encoding="utf-8")
    dart_header = "\n".join(dart_content.split("\n")[:10])
    assert "auto-generated" in dart_header, "Dart header should mention 'auto-generated'"

    # Test Docker generator
    docker_generator = DockerComposeGenerator()
    docker_file, _ = docker_generator.generate_to_file(temp_dir / "docker")
    docker_content = docker_file.read_text(encoding="utf-8")
    docker_header = "\n".join(docker_content.split("\n")[:10])
    assert "auto-generated" in docker_header, "Docker header should mention 'auto-generated'"


def test_python_header_format(temp_dir: Path, sample_schema: SchnitzelSchema) -> None:
    """Test that Python header has the correct format with all required elements."""
    generator = PythonModelGenerator()
    output_file, _ = generator.generate_to_file(
        sample_schema,
        temp_dir / "python",
        schema_source="test_schema.yaml"
    )

    content = output_file.read_text(encoding="utf-8")
    lines = content.split("\n")

    # Check for expected header components
    header_text = "\n".join(lines[:5])

    assert "# Generated by Schnitzel Framework" in header_text, \
        "Header should identify generator"
    assert "# DO NOT EDIT - This file is auto-generated" in header_text, \
        "Header should have explicit DO NOT EDIT warning"
    assert "# Generated at:" in header_text, \
        "Header should include generation timestamp"
    assert "# Source: test_schema.yaml" in header_text, \
        "Header should reference source schema file"


def test_dart_header_format(temp_dir: Path, sample_schema: SchnitzelSchema) -> None:
    """Test that Dart header has the correct format with all required elements."""
    generator = DartModelGenerator()
    output_file, _ = generator.generate_to_file(
        sample_schema,
        temp_dir / "dart",
        schema_source="test_schema.yaml"
    )

    content = output_file.read_text(encoding="utf-8")
    lines = content.split("\n")

    # Check for expected header components
    header_text = "\n".join(lines[:5])

    assert "// Generated by Schnitzel Framework" in header_text, \
        "Header should identify generator"
    assert "// DO NOT EDIT - This file is auto-generated" in header_text, \
        "Header should have explicit DO NOT EDIT warning"
    assert "// Generated at:" in header_text, \
        "Header should include generation timestamp"
    assert "// Source: test_schema.yaml" in header_text, \
        "Header should reference source schema file"


def test_docker_header_format(temp_dir: Path) -> None:
    """Test that Docker Compose header has the correct format with all required elements."""
    generator = DockerComposeGenerator()
    output_file, _ = generator.generate_to_file(temp_dir / "docker")

    content = output_file.read_text(encoding="utf-8")
    lines = content.split("\n")

    # Check for expected header components
    header_text = "\n".join(lines[:5])

    assert "# Generated by Schnitzel Framework" in header_text, \
        "Header should identify generator"
    assert "# DO NOT EDIT - This file is auto-generated" in header_text, \
        "Header should have explicit DO NOT EDIT warning"
    assert "# Generated at:" in header_text, \
        "Header should include generation timestamp"


def test_python_header_before_imports(temp_dir: Path, sample_schema: SchnitzelSchema) -> None:
    """Test that Python header appears before any import statements."""
    generator = PythonModelGenerator()
    output_file, _ = generator.generate_to_file(
        sample_schema,
        temp_dir / "python",
        schema_source="test_schema.yaml"
    )

    content = output_file.read_text(encoding="utf-8")
    lines = content.split("\n")

    # Find first import line
    first_import_index = None
    for i, line in enumerate(lines):
        if line.startswith("from ") or line.startswith("import "):
            first_import_index = i
            break

    assert first_import_index is not None, "Should have import statements"

    # Verify header comes before imports
    header_found = False
    for i in range(first_import_index):
        if "DO NOT EDIT" in lines[i]:
            header_found = True
            break

    assert header_found, "DO NOT EDIT header should appear before imports"


def test_dart_header_before_imports(temp_dir: Path, sample_schema: SchnitzelSchema) -> None:
    """Test that Dart header appears before any import statements."""
    generator = DartModelGenerator()
    output_file, _ = generator.generate_to_file(
        sample_schema,
        temp_dir / "dart",
        schema_source="test_schema.yaml"
    )

    content = output_file.read_text(encoding="utf-8")
    lines = content.split("\n")

    # Find first import line
    first_import_index = None
    for i, line in enumerate(lines):
        if line.startswith("import "):
            first_import_index = i
            break

    assert first_import_index is not None, "Should have import statements"

    # Verify header comes before imports
    header_found = False
    for i in range(first_import_index):
        if "DO NOT EDIT" in lines[i]:
            header_found = True
            break

    assert header_found, "DO NOT EDIT header should appear before imports"


def test_docker_header_before_content(temp_dir: Path) -> None:
    """Test that Docker Compose header appears before the version declaration."""
    generator = DockerComposeGenerator()
    output_file, _ = generator.generate_to_file(temp_dir / "docker")

    content = output_file.read_text(encoding="utf-8")
    lines = content.split("\n")

    # Find version line
    version_index = None
    for i, line in enumerate(lines):
        if line.startswith("version:"):
            version_index = i
            break

    assert version_index is not None, "Should have version declaration"

    # Verify header comes before version
    header_found = False
    for i in range(version_index):
        if "DO NOT EDIT" in lines[i]:
            header_found = True
            break

    assert header_found, "DO NOT EDIT header should appear before version declaration"


def test_header_timestamp_format(temp_dir: Path, sample_schema: SchnitzelSchema) -> None:
    """Test that headers include a timestamp in ISO format."""
    # Test Python
    python_generator = PythonModelGenerator()
    python_file, _ = python_generator.generate_to_file(
        sample_schema,
        temp_dir / "python",
        schema_source="test_schema.yaml"
    )
    python_content = python_file.read_text(encoding="utf-8")

    # Check for timestamp pattern (YYYY-MM-DD format)
    import re
    timestamp_pattern = r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}"
    assert re.search(timestamp_pattern, python_content), \
        "Python header should include ISO format timestamp"

    # Test Dart
    dart_generator = DartModelGenerator()
    dart_file, _ = dart_generator.generate_to_file(
        sample_schema,
        temp_dir / "dart",
        schema_source="test_schema.yaml"
    )
    dart_content = dart_file.read_text(encoding="utf-8")
    assert re.search(timestamp_pattern, dart_content), \
        "Dart header should include ISO format timestamp"

    # Test Docker
    docker_generator = DockerComposeGenerator()
    docker_file, _ = docker_generator.generate_to_file(temp_dir / "docker")
    docker_content = docker_file.read_text(encoding="utf-8")
    assert re.search(timestamp_pattern, docker_content), \
        "Docker header should include ISO format timestamp"


def test_multiple_generations_update_timestamp(temp_dir: Path, sample_schema: SchnitzelSchema) -> None:
    """Test that regenerating files updates the timestamp in the header."""
    import time

    # Generate once
    generator = PythonModelGenerator()
    output_file, _ = generator.generate_to_file(
        sample_schema,
        temp_dir / "python",
        schema_source="test_schema.yaml"
    )
    first_content = output_file.read_text(encoding="utf-8")

    # Extract first timestamp
    import re
    timestamp_pattern = r"Generated at: (.+)"
    first_match = re.search(timestamp_pattern, first_content)
    assert first_match, "Should have timestamp in first generation"
    first_timestamp = first_match.group(1)

    # Wait a bit to ensure timestamp changes
    time.sleep(0.1)

    # Generate again
    output_file, _ = generator.generate_to_file(
        sample_schema,
        temp_dir / "python",
        schema_source="test_schema.yaml"
    )
    second_content = output_file.read_text(encoding="utf-8")

    # Extract second timestamp
    second_match = re.search(timestamp_pattern, second_content)
    assert second_match, "Should have timestamp in second generation"
    second_timestamp = second_match.group(1)

    # Timestamps should be different (second should be later)
    assert first_timestamp != second_timestamp, \
        "Regenerating should update the timestamp"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
