"""Dart auth client generator for Schnitzel schemas.

Generates complete authentication client for Flutter/Dart applications with:
- AuthClient for login, register, logout, token refresh
- Secure token storage using flutter_secure_storage
- AuthInterceptor for Dio with auto token refresh
- AuthBloc for state management
- OAuth flow handlers (Google, Apple, Magic Link)
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List
from jinja2 import Environment, PackageLoader, select_autoescape

from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema


class DartAuthClientGenerator:
    """Generates Dart authentication client from Schnitzel schemas."""

    def __init__(self):
        """Initialize the Dart auth client generator."""
        self.env = Environment(
            loader=PackageLoader('schnitzel', 'templates/dart'),
            autoescape=select_autoescape(),
        )

    def generate(self, schema: SchnitzelSchema) -> Dict[str, str]:
        """
        Generate Dart auth client files from a schema.

        Extracts authentication configuration from the schema and generates:
        - auth_client.dart: Main AuthClient class with login/register/logout
        - token_storage.dart: Secure token storage using flutter_secure_storage
        - auth_interceptor.dart: Dio interceptor with auto token refresh
        - auth_bloc.dart: BLoC for auth state management
        - oauth_handler.dart: OAuth flows (Google, Apple, Magic Link)

        Args:
            schema: The Schnitzel schema to generate auth client from

        Returns:
            Dictionary mapping filename to generated code
        """
        # Extract auth configuration from schema
        auth_config = self._extract_auth_config(schema)

        # Generate all auth files
        files = {}

        # Generate main auth client
        template = self.env.get_template("auth_client.dart.j2")
        files["auth_client.dart"] = template.render(auth_config=auth_config)

        # Generate token storage
        template = self.env.get_template("token_storage.dart.j2")
        files["token_storage.dart"] = template.render(auth_config=auth_config)

        # Generate auth interceptor
        template = self.env.get_template("auth_interceptor.dart.j2")
        files["auth_interceptor.dart"] = template.render(auth_config=auth_config)

        # Generate auth BLoC
        template = self.env.get_template("auth_bloc.dart.j2")
        files["auth_bloc.dart"] = template.render(auth_config=auth_config)

        # Generate OAuth handler
        template = self.env.get_template("oauth_handler.dart.j2")
        files["oauth_handler.dart"] = template.render(auth_config=auth_config)

        return files

    def generate_to_files(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> List[tuple[Path, int]]:
        """
        Generate Dart auth client and write to multiple files.

        Creates the output directory if it doesn't exist, adds header comments with
        generation metadata, and writes all auth files to the specified directory.

        Args:
            schema: The Schnitzel schema to generate auth client from
            output_dir: Directory where files should be written (can be string or Path)
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            List of tuples (Path object pointing to file, size in bytes)

        Example:
            >>> generator = DartAuthClientGenerator()
            >>> files = generator.generate_to_files(schema, "packages/shared/lib/generated/auth")
            >>> for path, size in files:
            ...     print(f"Generated: {path} ({size} bytes)")
        """
        # Convert to Path object
        output_path = Path(output_dir)

        # Generate all auth files
        files_content = self.generate(schema)

        # Build header comment
        timestamp = datetime.now().isoformat()
        header = f"""// Generated by Schnitzel Framework v{__version__}
// DO NOT EDIT - This file is auto-generated
// Generated at: {timestamp}
// Source: {schema_source}

"""

        # Write all files
        result_files = []
        for filename, content in files_content.items():
            full_code = header + content
            file_path = output_path / filename
            file_size = len(full_code.encode("utf-8"))

            if dry_run:
                result_files.append((file_path, file_size))
                continue

            # Create directory if it doesn't exist
            output_path.mkdir(parents=True, exist_ok=True)

            # Warn if file already exists
            if file_path.exists():
                print(f"Warning: Overwriting existing file: {file_path}")

            file_path.write_text(full_code, encoding="utf-8")
            result_files.append((file_path, file_size))

        return result_files

    def _extract_auth_config(self, schema: SchnitzelSchema) -> Dict[str, Any]:
        """Extract authentication configuration from schema.

        Reads the auth section and extracts:
        - providers: List of auth providers (email_password, google, apple, magic_link, etc.)
        - jwt_config: JWT configuration (access_expiry, refresh_expiry, algorithm)
        - has_email_password: Whether email/password auth is enabled
        - has_google: Whether Google OAuth is enabled
        - has_apple: Whether Apple Sign In is enabled
        - has_magic_link: Whether magic link auth is enabled
        - oauth_callback_url: Base URL for OAuth callbacks
        - password_policy: Password requirements

        Args:
            schema: The Schnitzel schema

        Returns:
            Dictionary with auth configuration for template rendering
        """
        auth_config = {
            "providers": ["email_password"],
            "has_email_password": True,
            "has_google": False,
            "has_apple": False,
            "has_github": False,
            "has_discord": False,
            "has_microsoft": False,
            "has_magic_link": False,
            "oauth_callback_url": None,
            "jwt_config": {
                "access_expiry": 900,  # 15 minutes in seconds
                "refresh_expiry": 2592000,  # 30 days in seconds
                "algorithm": "HS256",
            },
            "password_policy": {
                "min_length": 8,
                "require_uppercase": False,
                "require_lowercase": False,
                "require_number": False,
                "require_special": False,
            },
            "base_url": "http://localhost:8000",
            "endpoints": {
                "login": "/auth/login",
                "register": "/auth/register",
                "logout": "/auth/logout",
                "refresh": "/auth/refresh",
                "me": "/auth/me",
            },
        }

        # Extract auth configuration if it exists
        if not schema.auth:
            return auth_config

        auth = schema.auth

        # Extract providers
        if hasattr(auth, "providers") and auth.providers:
            auth_config["providers"] = auth.providers
            auth_config["has_email_password"] = "email_password" in auth.providers
            auth_config["has_google"] = "google" in auth.providers
            auth_config["has_apple"] = "apple" in auth.providers
            auth_config["has_github"] = "github" in auth.providers
            auth_config["has_discord"] = "discord" in auth.providers
            auth_config["has_microsoft"] = "microsoft" in auth.providers
            auth_config["has_magic_link"] = "magic_link" in auth.providers

        # Extract OAuth callback URL
        if hasattr(auth, "oauth_callback_url") and auth.oauth_callback_url:
            auth_config["oauth_callback_url"] = auth.oauth_callback_url

        # Extract JWT configuration
        if hasattr(auth, "jwt") and auth.jwt:
            jwt = auth.jwt
            if hasattr(jwt, "access_expiry"):
                auth_config["jwt_config"]["access_expiry"] = jwt.access_expiry
            if hasattr(jwt, "refresh_expiry"):
                auth_config["jwt_config"]["refresh_expiry"] = jwt.refresh_expiry
            if hasattr(jwt, "algorithm"):
                auth_config["jwt_config"]["algorithm"] = jwt.algorithm

        # Extract password policy
        if hasattr(auth, "password_policy") and auth.password_policy:
            policy = auth.password_policy
            if hasattr(policy, "min_length"):
                auth_config["password_policy"]["min_length"] = policy.min_length
            if hasattr(policy, "require_uppercase"):
                auth_config["password_policy"]["require_uppercase"] = policy.require_uppercase
            if hasattr(policy, "require_lowercase"):
                auth_config["password_policy"]["require_lowercase"] = policy.require_lowercase
            if hasattr(policy, "require_number"):
                auth_config["password_policy"]["require_number"] = policy.require_number
            if hasattr(policy, "require_special"):
                auth_config["password_policy"]["require_special"] = policy.require_special

        return auth_config
