"""Dart BLoC state generator for Schnitzel schemas.

Generates BLoC pattern files (bloc, event, state) for Flutter state management.
"""

from datetime import datetime
from pathlib import Path
from typing import Dict
from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema, Model


class BlocStateGenerator:
    """Generates BLoC pattern files from Schnitzel schemas."""

    def __init__(self):
        """Initialize the BLoC state generator."""
        pass

    def _to_snake_case(self, name: str) -> str:
        """Convert PascalCase to snake_case.

        Args:
            name: The name to convert

        Returns:
            snake_case version of the name

        Examples:
            OrderBloc -> order_bloc
            UserProfile -> user_profile
        """
        result = []
        for i, char in enumerate(name):
            if char.isupper() and i > 0:
                # Add underscore before uppercase letter
                result.append('_')
                result.append(char.lower())
            else:
                result.append(char.lower())
        return ''.join(result)

    def generate(self, schema: SchnitzelSchema, model_name: str) -> Dict[str, str]:
        """Generate BLoC files for a specific model.

        Args:
            schema: The Schnitzel schema
            model_name: Name of the model to generate BLoC for (e.g., "Order", "User")

        Returns:
            Dictionary mapping file names to their content:
            {
                "order_bloc.dart": "...",
                "order_event.dart": "...",
                "order_state.dart": "..."
            }

        Raises:
            ValueError: If model_name is not found in schema
        """
        # Validate model exists
        if model_name not in schema.models:
            available = ", ".join(schema.models.keys())
            raise ValueError(
                f"Model '{model_name}' not found in schema. Available models: {available}"
            )

        model = schema.models[model_name]

        # Get package name for imports
        package_name = "app"
        if schema.meta:
            package_name = schema.meta.name.lower().replace('-', '_')
        shared_package = f"{package_name}_shared"

        # Generate file names
        snake_name = self._to_snake_case(model_name)
        bloc_file = f"{snake_name}_bloc.dart"
        event_file = f"{snake_name}_event.dart"
        state_file = f"{snake_name}_state.dart"

        # Generate content for each file
        return {
            bloc_file: self._generate_bloc_class(model_name, model, shared_package),
            event_file: self._generate_event_class(model_name, model, shared_package),
            state_file: self._generate_state_class(model_name, model, shared_package),
        }

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        model_name: str,
        output_dir: str | Path,
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> Dict[Path, int]:
        """Generate BLoC files and write them to disk.

        Creates the output directory if it doesn't exist and writes three files:
        - {model}_bloc.dart
        - {model}_event.dart
        - {model}_state.dart

        Args:
            schema: The Schnitzel schema
            model_name: Name of the model to generate BLoC for
            output_dir: Directory where files should be written (can be string or Path)
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            Dictionary mapping Path objects to file sizes in bytes

        Example:
            >>> generator = BlocStateGenerator()
            >>> files = generator.generate_to_file(schema, "Order", "packages/orders/lib/bloc")
            >>> for path, size in files.items():
            ...     print(f"{path.name}: {size} bytes")
        """
        # Convert to Path object
        output_path = Path(output_dir)

        # Generate the BLoC files
        files = self.generate(schema, model_name)

        # Build header comment
        timestamp = datetime.now().isoformat()
        header = f"""// Generated by Schnitzel Framework v{__version__}
// DO NOT EDIT - This file is auto-generated
// Generated at: {timestamp}
// Source: {schema_source}

"""

        # Write files and collect results
        result = {}
        for filename, content in files.items():
            full_code = header + content
            file_path = output_path / filename
            file_size = len(full_code.encode("utf-8"))

            # If dry-run, just record the info
            if dry_run:
                result[file_path] = file_size
                continue

            # Create directory if it doesn't exist
            output_path.mkdir(parents=True, exist_ok=True)

            # Warn if file already exists
            if file_path.exists():
                print(f"Warning: Overwriting existing file: {file_path}")

            file_path.write_text(full_code, encoding="utf-8")
            result[file_path] = file_size

        return result

    def _generate_bloc_class(self, model_name: str, model: Model, shared_package: str) -> str:
        """Generate the BLoC class file.

        Args:
            model_name: Name of the model (e.g., "Order")
            model: Model definition from schema
            shared_package: Name of the shared package for imports

        Returns:
            Dart BLoC class code
        """
        snake_name = self._to_snake_case(model_name)

        return f"""import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:{shared_package}/models/models.dart';
import '../repositories/repositories.dart';

part '{snake_name}_event.dart';
part '{snake_name}_state.dart';

/// BLoC for managing {model_name} state
class {model_name}Bloc extends Bloc<{model_name}Event, {model_name}State> {{
  final {model_name}Repository repository;

  {model_name}Bloc({{required this.repository}}) : super({model_name}Initial()) {{
    on<{model_name}Load>(_onLoad);
    on<{model_name}LoadById>(_onLoadById);
    on<{model_name}LoadMore>(_onLoadMore);
    on<{model_name}Filter>(_onFilter);
    on<{model_name}Sort>(_onSort);
    on<{model_name}Create>(_onCreate);
    on<{model_name}Update>(_onUpdate);
    on<{model_name}Delete>(_onDelete);
    on<{model_name}Refresh>(_onRefresh);
  }}

  Future<void> _onLoad({model_name}Load event, Emitter<{model_name}State> emit) async {{
    emit({model_name}Loading());
    try {{
      // Load from cache first for offline support
      final cachedItems = await repository.getAllFromCache();
      if (cachedItems.isNotEmpty) {{
        emit({model_name}Loaded(
          items: cachedItems,
          hasMore: false,
          currentPage: 1,
          isFromCache: true,
        ));
      }}

      // Fetch from API with pagination, filtering, and sorting
      final items = await repository.getAll(
        page: event.page,
        pageSize: event.pageSize,
        filters: event.filters,
        sortBy: event.sortBy,
        sortOrder: event.sortOrder,
      );

      // Update cache on success
      await repository.updateCache(items);

      emit({model_name}Loaded(
        items: items,
        hasMore: items.length >= event.pageSize,
        currentPage: event.page,
        currentFilters: event.filters,
        currentSortBy: event.sortBy,
        currentSortOrder: event.sortOrder,
      ));
    }} catch (error) {{
      // If we have cached data and API fails, keep showing cached data with error
      if (state is {model_name}Loaded) {{
        final currentState = state as {model_name}Loaded;
        if (currentState.isFromCache) {{
          return; // Keep cached data visible
        }}
      }}
      emit({model_name}Error(message: error.toString()));
    }}
  }}

  Future<void> _onLoadMore({model_name}LoadMore event, Emitter<{model_name}State> emit) async {{
    if (state is! {model_name}Loaded) return;

    final currentState = state as {model_name}Loaded;
    if (!currentState.hasMore) return;

    try {{
      final nextPage = currentState.currentPage + 1;
      final moreItems = await repository.getAll(
        page: nextPage,
        pageSize: event.pageSize,
        filters: currentState.currentFilters,
        sortBy: currentState.currentSortBy,
        sortOrder: currentState.currentSortOrder,
      );

      final updatedItems = List<{model_name}>.from(currentState.items)..addAll(moreItems);

      emit({model_name}Loaded(
        items: updatedItems,
        hasMore: moreItems.length >= event.pageSize,
        currentPage: nextPage,
        currentFilters: currentState.currentFilters,
        currentSortBy: currentState.currentSortBy,
        currentSortOrder: currentState.currentSortOrder,
      ));
    }} catch (error) {{
      // Keep current state and emit error separately
      emit({model_name}Error(message: error.toString()));
      emit(currentState);
    }}
  }}

  Future<void> _onFilter({model_name}Filter event, Emitter<{model_name}State> emit) async {{
    emit({model_name}Loading());
    try {{
      final items = await repository.getAll(
        page: 1,
        pageSize: event.pageSize,
        filters: event.filters,
        sortBy: state is {model_name}Loaded ? (state as {model_name}Loaded).currentSortBy : null,
        sortOrder: state is {model_name}Loaded ? (state as {model_name}Loaded).currentSortOrder : null,
      );

      emit({model_name}Loaded(
        items: items,
        hasMore: items.length >= event.pageSize,
        currentPage: 1,
        currentFilters: event.filters,
        currentSortBy: state is {model_name}Loaded ? (state as {model_name}Loaded).currentSortBy : null,
        currentSortOrder: state is {model_name}Loaded ? (state as {model_name}Loaded).currentSortOrder : null,
      ));
    }} catch (error) {{
      emit({model_name}Error(message: error.toString()));
    }}
  }}

  Future<void> _onSort({model_name}Sort event, Emitter<{model_name}State> emit) async {{
    emit({model_name}Loading());
    try {{
      final items = await repository.getAll(
        page: 1,
        pageSize: event.pageSize,
        filters: state is {model_name}Loaded ? (state as {model_name}Loaded).currentFilters : null,
        sortBy: event.sortBy,
        sortOrder: event.sortOrder,
      );

      emit({model_name}Loaded(
        items: items,
        hasMore: items.length >= event.pageSize,
        currentPage: 1,
        currentFilters: state is {model_name}Loaded ? (state as {model_name}Loaded).currentFilters : null,
        currentSortBy: event.sortBy,
        currentSortOrder: event.sortOrder,
      ));
    }} catch (error) {{
      emit({model_name}Error(message: error.toString()));
    }}
  }}

  Future<void> _onCreate({model_name}Create event, Emitter<{model_name}State> emit) async {{
    if (state is! {model_name}Loaded) return;

    final currentState = state as {model_name}Loaded;
    emit({model_name}Loading());

    try {{
      final created = await repository.create(event.item);

      // Optimistic update: add to existing list
      final updatedItems = List<{model_name}>.from(currentState.items)..add(created);
      emit({model_name}Loaded(items: updatedItems));
    }} catch (error) {{
      // Rollback to previous state on error
      emit(currentState);
      emit({model_name}Error(message: error.toString()));
    }}
  }}

  Future<void> _onUpdate({model_name}Update event, Emitter<{model_name}State> emit) async {{
    if (state is! {model_name}Loaded) return;

    final currentState = state as {model_name}Loaded;
    emit({model_name}Loading());

    try {{
      final updated = await repository.update(event.item);

      // Optimistic update: replace in existing list
      final updatedItems = currentState.items.map((item) {{
        // Assuming model has an 'id' field for comparison
        return item.id == updated.id ? updated : item;
      }}).toList();

      emit({model_name}Loaded(items: updatedItems));
    }} catch (error) {{
      // Rollback to previous state on error
      emit(currentState);
      emit({model_name}Error(message: error.toString()));
    }}
  }}

  Future<void> _onDelete({model_name}Delete event, Emitter<{model_name}State> emit) async {{
    if (state is! {model_name}Loaded) return;

    final currentState = state as {model_name}Loaded;
    emit({model_name}Loading());

    try {{
      await repository.delete(event.id);

      // Optimistic update: remove from existing list
      final updatedItems = currentState.items.where((item) => item.id != event.id).toList();
      emit({model_name}Loaded(items: updatedItems));
    }} catch (error) {{
      // Rollback to previous state on error
      emit(currentState);
      emit({model_name}Error(message: error.toString()));
    }}
  }}

  Future<void> _onRefresh({model_name}Refresh event, Emitter<{model_name}State> emit) async {{
    // Refresh without showing loading state
    try {{
      final items = await repository.getAll();
      emit({model_name}Loaded(items: items));
    }} catch (error) {{
      emit({model_name}Error(message: error.toString()));
    }}
  }}

  Future<void> _onLoadById({model_name}LoadById event, Emitter<{model_name}State> emit) async {{
    emit({model_name}Loading());
    try {{
      final item = await repository.getById(event.id);
      emit({model_name}DetailLoaded(item: item));
    }} catch (error) {{
      emit({model_name}Error(message: error.toString()));
    }}
  }}
}}
"""

    def _generate_event_class(self, model_name: str, model: Model, shared_package: str) -> str:
        """Generate the Event class file.

        Args:
            model_name: Name of the model (e.g., "Order")
            model: Model definition from schema
            shared_package: Name of the shared package (unused, part of inherits imports)

        Returns:
            Dart event classes code
        """
        snake_name = self._to_snake_case(model_name)

        return f"""part of '{snake_name}_bloc.dart';

/// Base event class for {model_name}
abstract class {model_name}Event extends Equatable {{
  const {model_name}Event();

  @override
  List<Object?> get props => [];
}}

/// Load all {model_name} items with pagination, filtering, and sorting
class {model_name}Load extends {model_name}Event {{
  final int page;
  final int pageSize;
  final Map<String, dynamic>? filters;
  final String? sortBy;
  final String? sortOrder;

  const {model_name}Load({{
    this.page = 1,
    this.pageSize = 20,
    this.filters,
    this.sortBy,
    this.sortOrder,
  }});

  @override
  List<Object?> get props => [page, pageSize, filters, sortBy, sortOrder];
}}

/// Load a single {model_name} by ID
class {model_name}LoadById extends {model_name}Event {{
  final String id;

  const {model_name}LoadById({{required this.id}});

  @override
  List<Object?> get props => [id];
}}

/// Load more {model_name} items for infinite scrolling
class {model_name}LoadMore extends {model_name}Event {{
  final int pageSize;

  const {model_name}LoadMore({{
    this.pageSize = 20,
  }});

  @override
  List<Object?> get props => [pageSize];
}}

/// Filter {model_name} items
class {model_name}Filter extends {model_name}Event {{
  final Map<String, dynamic> filters;
  final int pageSize;

  const {model_name}Filter({{
    required this.filters,
    this.pageSize = 20,
  }});

  @override
  List<Object?> get props => [filters, pageSize];
}}

/// Sort {model_name} items
class {model_name}Sort extends {model_name}Event {{
  final String sortBy;
  final String sortOrder;
  final int pageSize;

  const {model_name}Sort({{
    required this.sortBy,
    this.sortOrder = 'asc',
    this.pageSize = 20,
  }});

  @override
  List<Object?> get props => [sortBy, sortOrder, pageSize];
}}

/// Create a new {model_name}
class {model_name}Create extends {model_name}Event {{
  final {model_name} item;

  const {model_name}Create({{required this.item}});

  @override
  List<Object?> get props => [item];
}}

/// Update an existing {model_name}
class {model_name}Update extends {model_name}Event {{
  final {model_name} item;

  const {model_name}Update({{required this.item}});

  @override
  List<Object?> get props => [item];
}}

/// Delete a {model_name}
class {model_name}Delete extends {model_name}Event {{
  final String id;

  const {model_name}Delete({{required this.id}});

  @override
  List<Object?> get props => [id];
}}

/// Refresh {model_name} list without showing loading state
class {model_name}Refresh extends {model_name}Event {{
  const {model_name}Refresh();
}}
"""

    def _generate_state_class(self, model_name: str, model: Model, shared_package: str) -> str:
        """Generate the State class file.

        Args:
            model_name: Name of the model (e.g., "Order")
            model: Model definition from schema
            shared_package: Name of the shared package (unused, part of inherits imports)

        Returns:
            Dart state classes code
        """
        snake_name = self._to_snake_case(model_name)

        return f"""part of '{snake_name}_bloc.dart';

/// Base state class for {model_name}
abstract class {model_name}State extends Equatable {{
  const {model_name}State();

  @override
  List<Object?> get props => [];
}}

/// Initial state before any operation
class {model_name}Initial extends {model_name}State {{
  const {model_name}Initial();
}}

/// Loading state during async operations
class {model_name}Loading extends {model_name}State {{
  const {model_name}Loading();
}}

/// Loaded state with items, pagination, and filter info
class {model_name}Loaded extends {model_name}State {{
  final List<{model_name}> items;
  final bool hasMore;
  final int currentPage;
  final Map<String, dynamic>? currentFilters;
  final String? currentSortBy;
  final String? currentSortOrder;
  final bool isFromCache;

  const {model_name}Loaded({{
    required this.items,
    this.hasMore = false,
    this.currentPage = 1,
    this.currentFilters,
    this.currentSortBy,
    this.currentSortOrder,
    this.isFromCache = false,
  }});

  @override
  List<Object?> get props => [
        items,
        hasMore,
        currentPage,
        currentFilters,
        currentSortBy,
        currentSortOrder,
        isFromCache,
      ];
}}

/// Detail loaded state with single item
class {model_name}DetailLoaded extends {model_name}State {{
  final {model_name} item;

  const {model_name}DetailLoaded({{required this.item}});

  @override
  List<Object?> get props => [item];
}}

/// Error state with message
class {model_name}Error extends {model_name}State {{
  final String message;

  const {model_name}Error({{required this.message}});

  @override
  List<Object?> get props => [message];
}}
"""
