"""Async SQLAlchemy database configuration.

Generated by Schnitzel Framework v0.1.0
Generated at: 2025-12-05T18:40:40.041453

Provides async database session management for FastAPI with:
- Async engine with connection pooling
- Session factory for dependency injection
- get_db dependency for route handlers
"""

from collections.abc import AsyncGenerator
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase

from .settings import settings


# Create async database engine
engine = create_async_engine(
    settings.database_url,
    echo=settings.debug,
    pool_pre_ping=True,  # Enable connection health checks
    pool_size=5,
    max_overflow=10,
)

# Create async session factory
async_session_maker = async_sessionmaker(
    engine,
    class_=AsyncSession,
    expire_on_commit=False,
    autocommit=False,
    autoflush=False,
)


class Base(DeclarativeBase):
    """Base class for SQLAlchemy ORM models."""
    pass


async def get_db() -> AsyncGenerator[AsyncSession, None]:
    """
    FastAPI dependency that provides a database session.

    Yields an async session and ensures it's closed after the request.

    Usage:
        @router.get("/items")
        async def get_items(db: AsyncSession = Depends(get_db)):
            result = await db.execute(select(Item))
            return result.scalars().all()
    """
    async with async_session_maker() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise
        finally:
            await session.close()


async def init_db() -> None:
    """
    Initialize database tables.

    Creates all tables defined in ORM models that inherit from Base.
    Call this on application startup.
    """
    async with engine.begin() as conn:
        # Import ORM models to ensure they're registered with Base
        from .generated.orm import Base as ORMBase
        await conn.run_sync(ORMBase.metadata.create_all)


async def close_db() -> None:
    """
    Close database connections.

    Disposes of the connection pool. Call this on application shutdown.
    """
    await engine.dispose()
