# Generated by Schnitzel Framework v0.1.0
# DO NOT EDIT - This file is auto-generated
# Generated at: 2025-12-05T18:40:40.041752
# Source: schema.schnitzel.yaml

from __future__ import annotations

from datetime import datetime
from pydantic import BaseModel
from uuid import UUID


class User(BaseModel):
    """A user in the system"""

    # Fields
    id: UUID
    name: str
    email: str
    bio: str | None = None
    is_active: bool = True
    created_at: datetime

    # Relationships
    posts: list[Post] = []  # type: ignore[assignment]
    comments: list[Comment] = []  # type: ignore[assignment]

class Post(BaseModel):
    """A blog post"""

    # Fields
    id: UUID
    title: str
    content: str
    author_id: UUID
    created_at: datetime

    # Relationships
    author: User | None = None
    comments: list[Comment] = []  # type: ignore[assignment]

class Comment(BaseModel):
    """A comment on a post"""

    # Fields
    id: UUID
    content: str
    author_id: UUID
    post_id: UUID
    created_at: datetime

    # Relationships
    author: User | None = None
    post: Post | None = None
