"""Application settings using pydantic-settings.

Generated by Schnitzel Framework v0.1.0
Generated at: 2025-12-05T18:40:40.041118

Configuration is loaded from environment variables with fallback defaults.
Create a .env file in the backend directory to override settings.
"""

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application configuration with environment variable support."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
    )

    # Database configuration
    database_url: str = "postgresql+asyncpg://schnitzel:schnitzel@localhost:5432/schnitzel"

    # Application settings
    debug: bool = False
    app_name: str = "schnitzel"
    api_prefix: str = "/api"

    # CORS settings
    cors_origins: list[str] = ["*"]
    cors_allow_credentials: bool = True

    # Server settings
    host: str = "0.0.0.0"
    port: int = 8000


# Global settings instance
settings = Settings()
