"""Python JWT authentication generator for Schnitzel schemas.

Generates JWT token utilities including access/refresh token creation and verification.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict
from jinja2 import Environment, PackageLoader, select_autoescape

from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema


class JWTAuthGenerator:
    """Generates JWT authentication utilities from Schnitzel schemas."""

    def __init__(self):
        """Initialize the JWT auth generator."""
        self.env = Environment(
            loader=PackageLoader('schnitzel', 'templates/python'),
            autoescape=select_autoescape(),
        )

    def generate(self, schema: SchnitzelSchema) -> str:
        """
        Generate JWT authentication utilities from a schema.

        Extracts JWT configuration from the auth section and generates:
        - create_access_token(): Create short-lived access tokens
        - create_refresh_token(): Create long-lived refresh tokens
        - verify_token(): Verify and decode any JWT token
        - verify_access_token(): Verify specifically access tokens
        - verify_refresh_token(): Verify specifically refresh tokens

        Args:
            schema: The Schnitzel schema to generate JWT utilities from

        Returns:
            Generated Python code as a string
        """
        # Extract JWT configuration from schema
        jwt_config = self._extract_jwt_config(schema)

        # Load and render template
        template = self.env.get_template("auth/jwt.py.j2")
        rendered = template.render(jwt_config=jwt_config)
        return rendered

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate JWT authentication utilities and write them to a file.

        Creates the output directory if it doesn't exist, adds a header comment with
        generation metadata, and writes the JWT code to 'jwt.py' in the specified directory.

        Args:
            schema: The Schnitzel schema to generate JWT utilities from
            output_dir: Directory where jwt.py should be written (can be string or Path)
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            Tuple of (Path object pointing to jwt.py file, size in bytes)

        Example:
            >>> generator = JWTAuthGenerator()
            >>> output_path, size = generator.generate_to_file(schema, "backend/app/generated/auth")
            >>> print(f"JWT utilities written to: {output_path} ({size} bytes)")
        """
        # Convert to Path object
        output_path = Path(output_dir)

        # Generate the JWT code
        jwt_code = self.generate(schema)

        # Build header comment
        timestamp = datetime.now().isoformat()
        header = f"""# Generated by Schnitzel Framework v{__version__}
# DO NOT EDIT - This file is auto-generated
# Generated at: {timestamp}
# Source: {schema_source}

"""

        # Combine header with generated code
        full_code = header + jwt_code

        # Calculate file path and size
        jwt_file = output_path / "jwt.py"
        file_size = len(full_code.encode("utf-8"))

        # If dry-run, return without writing
        if dry_run:
            return jwt_file, file_size

        # Create directory if it doesn't exist
        output_path.mkdir(parents=True, exist_ok=True)

        # Warn if file already exists
        if jwt_file.exists():
            print(f"Warning: Overwriting existing file: {jwt_file}")

        jwt_file.write_text(full_code, encoding="utf-8")

        return jwt_file, file_size

    def _extract_jwt_config(self, schema: SchnitzelSchema) -> Dict[str, Any]:
        """Extract JWT configuration from schema.

        Reads the auth section and extracts:
        - secret_key: JWT signing secret (default: placeholder)
        - algorithm: Signing algorithm (default: HS256)
        - access_expiry: Access token expiration in minutes (from auth.session.access_expiry seconds)
        - refresh_expiry: Refresh token expiration in days (from auth.session.refresh_expiry seconds)

        Args:
            schema: The Schnitzel schema

        Returns:
            Dictionary with JWT configuration
        """
        jwt_config = {
            "secret_key": "your-secret-key-here-change-in-production",
            "algorithm": "HS256",
            "access_expiry": 15,  # minutes
            "refresh_expiry": 30,  # days
        }

        # Extract auth configuration if it exists
        if not schema.auth or not isinstance(schema.auth, dict):
            return jwt_config

        auth_config = schema.auth

        # Extract session configuration
        session_config = auth_config.get("session", {})
        if isinstance(session_config, dict):
            # Convert access_expiry from seconds to minutes
            if "access_expiry" in session_config:
                access_seconds = session_config["access_expiry"]
                jwt_config["access_expiry"] = max(1, access_seconds // 60)

            # Convert refresh_expiry from seconds to days
            if "refresh_expiry" in session_config:
                refresh_seconds = session_config["refresh_expiry"]
                jwt_config["refresh_expiry"] = max(1, refresh_seconds // 86400)

        # Note: secret_key and algorithm are typically set via environment variables
        # or configuration files, not in the schema

        return jwt_config
