"""Python MFA (Multi-Factor Authentication) generator for Schnitzel schemas.

Generates TOTP-based MFA utilities including secret generation, verification, and QR code generation.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict
from jinja2 import Environment, PackageLoader, select_autoescape

from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema


class MFAGenerator:
    """Generates MFA utilities from Schnitzel schemas."""

    def __init__(self):
        """Initialize the MFA generator."""
        self.env = Environment(
            loader=PackageLoader('schnitzel', 'templates/python'),
            autoescape=select_autoescape(),
        )

    def generate(self, schema: SchnitzelSchema) -> str:
        """
        Generate MFA utilities from a schema.

        Extracts MFA configuration from the auth section and generates:
        - generate_totp_secret(): Create base32-encoded TOTP secret
        - verify_totp(): Verify TOTP code against secret
        - generate_totp_uri(): Generate otpauth:// URI for QR codes
        - generate_qr_code(): Generate QR code PNG image data
        - generate_backup_codes(): Generate secure backup codes
        - hash_backup_codes(): Hash backup codes for storage
        - verify_backup_code(): Verify and consume backup codes
        - start_mfa_enrollment(): Begin MFA setup flow
        - complete_mfa_setup(): Finish MFA setup with verification
        - require_mfa(): FastAPI dependency for MFA verification
        - disable_mfa(): Disable MFA with authentication

        Args:
            schema: The Schnitzel schema to generate MFA utilities from

        Returns:
            Generated Python code as a string
        """
        # Extract MFA configuration from schema
        mfa_config = self._extract_mfa_config(schema)

        # Load and render template
        template = self.env.get_template("auth/mfa.py.j2")
        rendered = template.render(mfa_config=mfa_config)
        return rendered

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate MFA utilities and write them to a file.

        Creates the output directory if it doesn't exist, adds a header comment with
        generation metadata, and writes the MFA code to 'mfa.py' in the specified directory.

        Args:
            schema: The Schnitzel schema to generate MFA utilities from
            output_dir: Directory where mfa.py should be written (can be string or Path)
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            Tuple of (Path object pointing to mfa.py file, size in bytes)

        Example:
            >>> generator = MFAGenerator()
            >>> output_path, size = generator.generate_to_file(schema, "backend/app/generated/auth")
            >>> print(f"MFA utilities written to: {output_path} ({size} bytes)")
        """
        # Convert to Path object
        output_path = Path(output_dir)

        # Generate the MFA code
        mfa_code = self.generate(schema)

        # Build header comment
        timestamp = datetime.now().isoformat()
        header = f"""# Generated by Schnitzel Framework v{__version__}
# DO NOT EDIT - This file is auto-generated
# Generated at: {timestamp}
# Source: {schema_source}

"""

        # Combine header with generated code
        full_code = header + mfa_code

        # Calculate file path and size
        mfa_file = output_path / "mfa.py"
        file_size = len(full_code.encode("utf-8"))

        # If dry-run, return without writing
        if dry_run:
            return mfa_file, file_size

        # Create directory if it doesn't exist
        output_path.mkdir(parents=True, exist_ok=True)

        # Warn if file already exists
        if mfa_file.exists():
            print(f"Warning: Overwriting existing file: {mfa_file}")

        mfa_file.write_text(full_code, encoding="utf-8")

        return mfa_file, file_size

    def _extract_mfa_config(self, schema: SchnitzelSchema) -> Dict[str, Any]:
        """Extract MFA configuration from schema.

        Reads the auth section and extracts:
        - enabled: Whether MFA is enabled (default: False)
        - required: Whether MFA is required for all users (default: False)
        - methods: List of MFA methods supported (default: ["totp"])
        - backup_codes_count: Number of backup codes to generate (default: 10)
        - totp_issuer: Issuer name for TOTP apps (default: "MyApp")

        Args:
            schema: The Schnitzel schema

        Returns:
            Dictionary with MFA configuration
        """
        mfa_config = {
            "enabled": False,
            "required": False,
            "methods": ["totp"],
            "backup_codes_count": 10,
            "totp_issuer": "MyApp",
        }

        # Extract auth configuration if it exists
        if not schema.auth:
            return mfa_config

        auth_config = schema.auth

        # Extract MFA-specific configuration from AuthConfig Pydantic model
        if hasattr(auth_config, "mfa") and auth_config.mfa:
            mfa_section = auth_config.mfa

            # Extract enabled flag
            if hasattr(mfa_section, "enabled"):
                mfa_config["enabled"] = mfa_section.enabled

            # Extract required flag
            if hasattr(mfa_section, "required"):
                mfa_config["required"] = mfa_section.required

            # Extract methods list
            if hasattr(mfa_section, "methods"):
                mfa_config["methods"] = mfa_section.methods

            # Extract backup codes count
            if hasattr(mfa_section, "backup_codes_count"):
                mfa_config["backup_codes_count"] = mfa_section.backup_codes_count

            # Extract TOTP issuer
            if hasattr(mfa_section, "totp_issuer") and mfa_section.totp_issuer:
                mfa_config["totp_issuer"] = mfa_section.totp_issuer

        return mfa_config
