"""Python OAuth integration generator for Schnitzel schemas.

Generates OAuth flows for multiple providers including Google, Apple, and magic links.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List
from jinja2 import Environment, PackageLoader, select_autoescape

from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema


class OAuthIntegrationGenerator:
    """Generates OAuth integration utilities from Schnitzel schemas."""

    def __init__(self):
        """Initialize the OAuth integration generator."""
        self.env = Environment(
            loader=PackageLoader('schnitzel', 'templates/python'),
            autoescape=select_autoescape(),
        )

    def generate(self, schema: SchnitzelSchema) -> str:
        """
        Generate OAuth integration utilities from a schema.

        Extracts OAuth provider configuration from the auth.providers section and generates:
        - Google OAuth 2.0 flow (authorization URL, callback, user info)
        - Apple Sign In flow (authorization URL, callback, JWT decoding)
        - Magic link email flow (generation, verification, email sending)

        Each provider is conditionally included based on the schema configuration.

        Args:
            schema: The Schnitzel schema to generate OAuth utilities from

        Returns:
            Generated Python code as a string
        """
        # Extract OAuth configuration from schema
        oauth_config = self._extract_oauth_config(schema)

        # Load and render template
        template = self.env.get_template("auth/oauth.py.j2")
        rendered = template.render(oauth_config=oauth_config)
        return rendered

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate OAuth integration utilities and write them to a file.

        Creates the output directory if it doesn't exist, adds a header comment with
        generation metadata, and writes the OAuth code to 'oauth.py' in the specified directory.

        Args:
            schema: The Schnitzel schema to generate OAuth utilities from
            output_dir: Directory where oauth.py should be written (can be string or Path)
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            Tuple of (Path object pointing to oauth.py file, size in bytes)

        Example:
            >>> generator = OAuthIntegrationGenerator()
            >>> output_path, size = generator.generate_to_file(schema, "backend/app/generated/auth")
            >>> print(f"OAuth utilities written to: {output_path} ({size} bytes)")
        """
        # Convert to Path object
        output_path = Path(output_dir)

        # Generate the OAuth code
        oauth_code = self.generate(schema)

        # Build header comment
        timestamp = datetime.now().isoformat()
        header = f"""# Generated by Schnitzel Framework v{__version__}
# DO NOT EDIT - This file is auto-generated
# Generated at: {timestamp}
# Source: {schema_source}

"""

        # Combine header with generated code
        full_code = header + oauth_code

        # Calculate file path and size
        oauth_file = output_path / "oauth.py"
        file_size = len(full_code.encode("utf-8"))

        # If dry-run, return without writing
        if dry_run:
            return oauth_file, file_size

        # Create directory if it doesn't exist
        output_path.mkdir(parents=True, exist_ok=True)

        # Warn if file already exists
        if oauth_file.exists():
            print(f"Warning: Overwriting existing file: {oauth_file}")

        oauth_file.write_text(full_code, encoding="utf-8")

        return oauth_file, file_size

    def _extract_oauth_config(self, schema: SchnitzelSchema) -> Dict[str, Any]:
        """Extract OAuth configuration from schema.

        Reads the auth section and extracts:
        - providers: List of enabled authentication providers
        - has_google: Whether Google OAuth is enabled
        - has_apple: Whether Apple Sign In is enabled
        - has_magic_link: Whether magic link authentication is enabled
        - callback_url: Base URL for OAuth callbacks

        Args:
            schema: The Schnitzel schema

        Returns:
            Dictionary with OAuth configuration
        """
        oauth_config: Dict[str, Any] = {
            "providers": ["email_password"],
            "has_google": False,
            "has_apple": False,
            "has_magic_link": False,
            "has_email_password": False,
            "callback_url": "http://localhost:8000/auth/callback",
        }

        # Extract auth configuration if it exists
        if not schema.auth or not isinstance(schema.auth, dict):
            return oauth_config

        auth_config = schema.auth

        # Extract providers list
        providers: List[str] = auth_config.get("providers", ["email_password"])
        oauth_config["providers"] = providers

        # Set flags for each provider type
        oauth_config["has_google"] = "google" in providers
        oauth_config["has_apple"] = "apple" in providers
        oauth_config["has_magic_link"] = "magic_link" in providers
        oauth_config["has_email_password"] = "email_password" in providers

        # Extract callback URL if provided
        if "oauth_callback_url" in auth_config:
            oauth_config["callback_url"] = auth_config["oauth_callback_url"]

        return oauth_config
