"""Python RBAC permission generator for Schnitzel schemas.

Generates role-based access control utilities including role definitions,
permission checking, and wildcard/scoped permission support.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List
from jinja2 import Environment, PackageLoader, select_autoescape

from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema, RoleConfig


class RBACPermissionGenerator:
    """Generates RBAC permission utilities from Schnitzel schemas."""

    def __init__(self):
        """Initialize the RBAC permission generator."""
        self.env = Environment(
            loader=PackageLoader('schnitzel', 'templates/python'),
            autoescape=select_autoescape(),
        )

    def generate(self, schema: SchnitzelSchema) -> str:
        """
        Generate RBAC permission utilities from a schema.

        Extracts role configuration from the roles section and generates:
        - Role class: Defines roles with name, permissions, and inheritance
        - RoleRegistry: Manages role definitions with inheritance resolution
        - has_permission(): Check if user has a specific permission
        - has_any_permission(): Check if user has any of multiple permissions
        - has_all_permissions(): Check if user has all of multiple permissions
        - require_permission(): FastAPI dependency for permission enforcement
        - Wildcard support: "*" grants all permissions
        - Scoped permissions: "resource:action:scope" format support
        - Role inheritance: Child roles inherit parent permissions

        Args:
            schema: The Schnitzel schema to generate RBAC utilities from

        Returns:
            Generated Python code as a string
        """
        # Extract roles configuration from schema
        roles_config = self._extract_roles_config(schema)

        # Load and render template
        template = self.env.get_template("auth/rbac.py.j2")
        rendered = template.render(roles=roles_config)
        return rendered

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate RBAC permission utilities and write them to a file.

        Creates the output directory if it doesn't exist, adds a header comment with
        generation metadata, and writes the RBAC code to 'rbac.py' in the specified directory.

        Args:
            schema: The Schnitzel schema to generate RBAC utilities from
            output_dir: Directory where rbac.py should be written (can be string or Path)
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            Tuple of (Path object pointing to rbac.py file, size in bytes)

        Example:
            >>> generator = RBACPermissionGenerator()
            >>> output_path, size = generator.generate_to_file(schema, "backend/app/generated/auth")
            >>> print(f"RBAC utilities written to: {output_path} ({size} bytes)")
        """
        # Convert to Path object
        output_path = Path(output_dir)

        # Generate the RBAC code
        rbac_code = self.generate(schema)

        # Build header comment
        timestamp = datetime.now().isoformat()
        header = f"""# Generated by Schnitzel Framework v{__version__}
# DO NOT EDIT - This file is auto-generated
# Generated at: {timestamp}
# Source: {schema_source}

"""

        # Combine header with generated code
        full_code = header + rbac_code

        # Calculate file path and size
        rbac_file = output_path / "rbac.py"
        file_size = len(full_code.encode("utf-8"))

        # If dry-run, return without writing
        if dry_run:
            return rbac_file, file_size

        # Create directory if it doesn't exist
        output_path.mkdir(parents=True, exist_ok=True)

        # Warn if file already exists
        if rbac_file.exists():
            print(f"Warning: Overwriting existing file: {rbac_file}")

        rbac_file.write_text(full_code, encoding="utf-8")

        return rbac_file, file_size

    def _extract_roles_config(self, schema: SchnitzelSchema) -> List[Dict[str, Any]]:
        """Extract roles configuration from schema.

        Reads the roles section and extracts role definitions including:
        - name: Role identifier
        - description: Optional role description
        - permissions: List of permissions granted to this role
        - inherits: List of parent roles to inherit permissions from

        The roles are returned as a list of dictionaries for template rendering.
        Role inheritance is preserved so the template can handle resolution.

        Args:
            schema: The Schnitzel schema

        Returns:
            List of role configuration dictionaries

        Example:
            >>> roles = self._extract_roles_config(schema)
            >>> roles
            [
                {
                    'name': 'admin',
                    'description': 'Administrator role',
                    'permissions': ['*'],
                    'inherits': []
                },
                {
                    'name': 'moderator',
                    'description': 'Content moderator',
                    'permissions': ['users:read', 'content:*'],
                    'inherits': ['user']
                },
                {
                    'name': 'user',
                    'description': 'Regular user',
                    'permissions': ['content:read', 'content:create:own'],
                    'inherits': []
                }
            ]
        """
        roles_list = []

        # Extract roles configuration if it exists
        if not schema.roles:
            # Return default role configuration if no roles defined
            return [
                {
                    "name": "user",
                    "description": "Default user role",
                    "permissions": [],
                    "inherits": [],
                }
            ]

        # Convert RoleConfig instances to dictionaries for template
        for role_name, role_config in schema.roles.items():
            # role_config is a RoleConfig instance from Pydantic
            role_dict = {
                "name": role_config.name,
                "description": role_config.description or f"{role_config.name} role",
                "permissions": role_config.permissions or [],
                "inherits": role_config.inherits or [],
            }
            roles_list.append(role_dict)

        return roles_list
