"""Python session management generator for Schnitzel schemas.

Generates Redis-based session store with support for session expiry and sliding expiration.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict
from jinja2 import Environment, PackageLoader, select_autoescape

from schnitzel import __version__
from schnitzel.schema.models import SchnitzelSchema


class SessionManagementGenerator:
    """Generates session management utilities from Schnitzel schemas."""

    def __init__(self):
        """Initialize the session management generator."""
        self.env = Environment(
            loader=PackageLoader('schnitzel', 'templates/python'),
            autoescape=select_autoescape(),
        )

    def generate(self, schema: SchnitzelSchema) -> str:
        """
        Generate session management utilities from a schema.

        Extracts session configuration from the auth section and generates:
        - SessionStore class with Redis client
        - create_session(): Create session with unique ID and store user data
        - get_session(): Retrieve session data
        - update_session(): Update session data
        - delete_session(): Delete session
        - refresh_session(): Refresh session TTL for sliding expiration

        Args:
            schema: The Schnitzel schema to generate session utilities from

        Returns:
            Generated Python code as a string
        """
        # Extract session configuration from schema
        session_config = self._extract_session_config(schema)

        # Load and render template
        template = self.env.get_template("auth/sessions.py.j2")
        rendered = template.render(session_config=session_config)
        return rendered

    def generate_to_file(
        self,
        schema: SchnitzelSchema,
        output_dir: str | Path,
        schema_source: str = "schema.schnitzel.yaml",
        dry_run: bool = False,
    ) -> tuple[Path, int]:
        """
        Generate session management utilities and write them to a file.

        Creates the output directory if it doesn't exist, adds a header comment with
        generation metadata, and writes the session code to 'sessions.py' in the specified directory.

        Args:
            schema: The Schnitzel schema to generate session utilities from
            output_dir: Directory where sessions.py should be written (can be string or Path)
            schema_source: Optional name of the source schema file for documentation
            dry_run: If True, return file info without writing (default: False)

        Returns:
            Tuple of (Path object pointing to sessions.py file, size in bytes)

        Example:
            >>> generator = SessionManagementGenerator()
            >>> output_path, size = generator.generate_to_file(schema, "backend/app/generated/auth")
            >>> print(f"Session utilities written to: {output_path} ({size} bytes)")
        """
        # Convert to Path object
        output_path = Path(output_dir)

        # Generate the session code
        session_code = self.generate(schema)

        # Build header comment
        timestamp = datetime.now().isoformat()
        header = f"""# Generated by Schnitzel Framework v{__version__}
# DO NOT EDIT - This file is auto-generated
# Generated at: {timestamp}
# Source: {schema_source}

"""

        # Combine header with generated code
        full_code = header + session_code

        # Calculate file path and size
        session_file = output_path / "sessions.py"
        file_size = len(full_code.encode("utf-8"))

        # If dry-run, return without writing
        if dry_run:
            return session_file, file_size

        # Create directory if it doesn't exist
        output_path.mkdir(parents=True, exist_ok=True)

        # Warn if file already exists
        if session_file.exists():
            print(f"Warning: Overwriting existing file: {session_file}")

        session_file.write_text(full_code, encoding="utf-8")

        return session_file, file_size

    def _extract_session_config(self, schema: SchnitzelSchema) -> Dict[str, Any]:
        """Extract session configuration from schema.

        Reads the auth.session section and extracts:
        - storage: Storage backend (redis, memory, database)
        - expiry: Session expiration in seconds
        - sliding_window: Whether to extend session on activity
        - multi_device: Whether to allow multiple sessions per user
        - remember_me_duration: Extended session duration for remember me

        Args:
            schema: The Schnitzel schema

        Returns:
            Dictionary with session configuration
        """
        session_config = {
            "storage": "redis",
            "expiry": 3600,  # 1 hour in seconds
            "sliding_window": True,
            "multi_device": True,
            "remember_me_duration": None,
        }

        # Extract auth configuration if it exists
        if not schema.auth:
            return session_config

        auth_config = schema.auth

        # Extract session-specific configuration from AuthConfig Pydantic model
        if hasattr(auth_config, "session") and auth_config.session:
            session_section = auth_config.session

            # Extract storage backend
            if hasattr(session_section, "storage"):
                session_config["storage"] = session_section.storage

            # Extract expiry in seconds
            if hasattr(session_section, "expiry"):
                session_config["expiry"] = session_section.expiry

            # Extract sliding window configuration
            if hasattr(session_section, "sliding_window"):
                session_config["sliding_window"] = session_section.sliding_window

            # Extract multi-device configuration
            if hasattr(session_section, "multi_device"):
                session_config["multi_device"] = session_section.multi_device

            # Extract remember me duration
            if hasattr(session_section, "remember_me_duration") and session_section.remember_me_duration:
                session_config["remember_me_duration"] = session_section.remember_me_duration

        return session_config
